NixOS/hydra

src/root/plain-reload.tt
src/root/static/css/hydra.css

Constrain the visual height of tail-reload outputs to 50 lines. The lines already get capped to 50 lines by the backend, but the backend has no way of knowing the maximum font width, so we're capping it using JavaScript now.
Also, if the build output contains HTML (and possibly something like `<script>`), it wasn't escaped properly, which is fixed now as well.

Improvements of tail-reload output

---

release.nix

Hydra won't build via the instructions at https://nixos.org/wiki/Installing_hydra_as_nixos_module#Letting_nix_handle_the_git_repository without this change.
Specifically where it says "# or i686-linux if appropriate", there is an attribute not found error for i686.
With this change, and after setting up the "hydra" postgres user's password manually, I have Hydra up and running on my i686 laptop without issue.

Allow running on i686-linux

---

src/root/common.tt

If Hydra isn't hosted on `https://example.com/` but something like `https://example.com/hydra/`, the URL for `/api/scmdiff` would have ended up on `/api/scmdiff` rather than `/hydra/api/scmdiff`.
This is because we didn't use the URI resolver from the controller, hence we're using it now to build up the whole URL including the query string.

common.tt: Properly generate URL for /api/scmdiff.

---

src/hydra-eval-jobs/hydra-eval-jobs.cc

If there is no input named 'inputs', hydra-eval-jobs now passes in a set
of lists, where each attribute corresponds to an input defined in the
jobset specification and each list element is a different input alt, as
an argument named 'inputs'.
Among other things, this allows for generic hydra expressions to be
shared amongst projects with similar structures but different sets of
specific inputs.

hydra-eval-jobs: Pass all inputs as 'inputs' arg.

---

src/lib/Hydra/Helper/AddBuilds.pm

This allows importing the .drv and getting the same store paths as if the
input had been passed in as nix expressions defining a proper derivation.

Pass along drvPath and outputName for inputs that are previous builds.

---

src/lib/Hydra/Controller/Build.pm

When using Hydra behind a reverse proxy the tail-reload page does not work because of an incorrect URI.

Construct uri using uri_for, which respects X-Request-Base.

---

hydra-module.nix
src/lib/Hydra/Plugin/SlackNotification.pm

Respects `<slack>` blocks in the hydra config, with attributes:
* jobs: a regexp matching the job name (in the format project:jobset:job)
* url: The URL to a slack incoming webhook
* force: If true, always send messages. Otherwise, only when the build status changes
Multiple `<slack>` blocks are allowed

Add slack plugin.

---

hydra-module.nix

In one of my private instances, I want to build stuff on localhost. Unfortunately, it seems to get stuck and the queue-runner log reports the following:
`/nix/store/0naxglgmy5cpg0qghmznha1s700pifvd-bash-4.3.tar.gz.drv’ on ‘localhost’: cannot connect to ‘localhost’: error: cannot start ssh: No such file or directory`
Further inspection with strace reveals the following:
[pid  3309] execve("/nix/store/m04qal8fw9pchqj4h5q9m54hvqh4grrd-systemd-229/bin/nix-store", ["nix-store", "--serve", "--write"], [/* 53 vars */]) = -1 ENOENT (No such file or directory)
[pid  3309] execve("/nix/store/qq1rk7zyap4rwwyswcz0wi03a05m1d90-hydra-0.1.1234.abcdef/sbin/nix-store", ["nix-store", "--serve", "--write"], [/* 53 vars */]) = -1 ENOENT (No such file or directory)
[pid  3309] …

Fix problem with delegating builds to localhost due to nix-store not being in the PATH

---

src/hydra-queue-runner/builder.cc
src/hydra-queue-runner/hydra-queue-runner.cc
src/hydra-queue-runner/state.hh
src/lib/Hydra/Helper/PluginHooks.pm
src/lib/Hydra/Plugin.pm
src/lib/Hydra/Plugin/GithubStatus.pm
src/script/hydra-notify

Mutliple `<githubstatus>` sections are possible:
* jobs: regexp for jobs to match
* inputs: the input which corresponds to the github repo/rev whose
status we want to report. Can be repeated
* authorization: Verbatim contents of the Authorization header. See
https://developer.github.com/v3/#authentication.

Add a plugin to interact with the github status API.

---

release.nix

makeBinPath takes care to use the correct output.
nix-repl> lib.makeSearchPath "bin" [pkgs.nix]
"/nix/store/zpp83pr21ihxwsr15l6mkzwkr49zj71d-nix-1.11.2-dev/bin"
nix-repl> lib.makeBinPath [pkgs.nix]
"/nix/store/9n8c3g541qn43yjjs94f1a0m69wp8scg-nix-1.11.2/bin"

release.nix use makeBinPath to construct PATH

---

src/lib/Hydra/Controller/Jobset.pm
src/lib/Hydra/Controller/Project.pm
src/lib/Hydra/Helper/AddBuilds.pm
src/lib/Hydra/Helper/CatalystUtils.pm
src/lib/Hydra/Schema/Projects.pm
src/root/edit-project.tt
src/root/jobset.tt
src/root/project.tt
src/script/hydra-evaluator
src/script/hydra-notify
src/sql/hydra.sql
src/sql/upgrade-48.sql

This allows fully declarative project specifications. This is best
illustrated by example:
* I create a new project, setting the declarative spec file to
"spec.json" and the declarative input to a git repo pointing
at git://github.com/shlevy/declarative-hydra-example.git
* hydra creates a special ".jobsets" jobset alongside the project
* Just before evaluating the ".jobsets" jobset, hydra fetches
declarative-hydra-example.git, reads spec.json as a jobset spec,
and updates the jobset's configuration accordingly:
```json
{
"enabled": 1,
"hidden": false,
"description": "Jobsets",
"nixexprinput": "src",
"nixexprpath": "default.nix",
"checkinterval": 300,
"schedulingshares": 100,
"enableemail": false,
"emailoverride": "",
"keepnr": 3,
"inputs": {
"src": { "type": "git", "value": …
```

Enable declarative projects.

---

hydra-module.nix

Gives users who want to use binary caches a way to do so without messing with
module internals. See https://github.com/NixOS/hydra/issues/297 for details.

hydra-module.nix: add 'useSubstitutes' option to control use of binary caches

---

hydra-module.nix

Without this I get:
```
error: value is a function while a Boolean was expected
```

hydra-module: fix useSubstitutes configuration option

---

src/lib/Hydra/Controller/API.pm

URLs like "git@github.com:owner/repo.git
This commit removes the need for a forward slash between 'github.com' and
'owner'.

Trigger ssh like urls from github pushes

---

hydra-module.nix
release.nix
src/lib/Hydra/View/NARInfo.pm
src/lib/Hydra/View/NixNAR.pm

According to following two benchmarks:
- https://www.rootusers.com/gzip-vs-bzip2-vs-xz-performance-comparison/
- http://catchchallenger.first-world.info/wiki/Quick_Benchmark:_Gzip_vs_Bzip2_vs_LZMA_vs_XZ_vs_LZ4_vs_LZO
xz has better compression ratio than bzip2 at lowest compression rate.
https://github.com/vasi/pixz has been chosen as it can scale compressing
over multiple cores linearly.
We're using this in snabblab for a month now and it has improved CPU
wise the main Hydra server.
cc @edolstra

Use pixz instead of bzip2 for compressing nars

---

src/root/edit-jobset.tt
src/root/jobset.tt

When having a huge input table, it's really hard to reason about inputs when they're not sorted every time you want to edit them. This PR sorts them by name:
Fixes https://github.com/NixOS/hydra/issues/371
cc  @edolstra

Sort inputs table

---

src/lib/Hydra/Controller/API.pm

This is based on #331 
It will trigger builds where the repository name has the the pushed repository name as a prefix. This was a problem before if the repository name had `.git` in it too.

GitHub push suffix

---

src/lib/Hydra/Helper/Nix.pm

This enables the include syntax `include filename`. At the moment only `<<include filename>>` is allowed.
This also seems to enable absolute paths as filenames, but I can't find any documentation saying that.

Enable apache style includes in the config file

---

hydra-module.nix

See https://github.com/NixOS/nixpkgs/pull/17469 for motivation.
Relevant parts:
---
Currently `nix.buildMachines` remotes are listed in "Machine Status" and enabled in "Manage machines" but won't be used because `hydra.buildMachinesFiles` is empty by default.
This adds `/etc/nix/machines` in the default `hydra.buildMachinesFiles` so remotes defined in`nix.buildMachines` are used without explicit configuration.
---
I suppose upstream Hydra has the same issue. 
```
NIX_REMOTE_SYSTEMS = concatStringsSep ":" cfg.buildMachinesFiles;
```
So if `buildMachinesFiles` is empty, `NIX_REMOTE_SYSTEMS` will be empty too.
On the other hand, Hydra uses `/etc/nix/machines` when `NIX_REMOTE_SYSTEMS` is empty, see  https://github.com/NixOS/hydra/blob/master/src/lib/Hydra/Helper/Nix.pm#L306
So if I …

module: add default to buildMachinesFiles

---

hydra-module.nix

@shlevy without this I got the following error in my journal when trying out a declarative project:
```
Oct 25 22:42:29 mymachine hydra-evaluator[4085]: starting evaluation of jobset ‘myproject:.jobsets’
Oct 25 22:42:29 mymachine hydra-evaluator[4085]: timeout: failed to run command ‘hydra-eval-jobset’: No such file or directory
Oct 25 22:42:29 mymachine hydra-evaluator[4085]: evaluation of jobset ‘myproject:.jobsets’ finished with status 32512
```

Allow hydra-eval-jobset to be found by the hydra-evaluator

---

doc/manual/declarative-projects.xml
doc/manual/projects.xml

Conversion of Shea's *.md, added as a subsection.  Shea is left as author.
I made this new bit a separate file, though it might be questionable.

doc: add basic docs about declarative projects

---

src/root/layout.tt

It is no longer used and causes unnecessary 404s

Remove logfile.css from templates

---

doc/manual/projects.xml

Manual builds correctly on my machine and I have been using the code snippets on my hydra instance for a few days without problems.

Document ssmtp for email notifications.

---

src/hydra-eval-jobs/hydra-eval-jobs.cc

For some reason this causes an unexpected EOF when doing import-from-derivation.

hydra-eval-jobs: Disable the build hook.

---

src/lib/Hydra/View/NixExprs.pm

Fixes the problem described in #254 for me. \o/

NixExprs.pm: encode default.nix as utf-8 to fix missing chars/data.

---

doc/manual/api.xml
doc/manual/manual.xml

Closes #440 and implements the information in that issue as official documentation instead.
This PR documents the how to:
- List projects
- Get a single project
- Get a single job set
- List evaluations
- Get a single build
I does not document how to:
- Authenticate
- Get the current user profile
- Create a project
- Create a job set
The reason why is because I got a build error when I tried installing hydra
locally, so I couldn't try out those endpoints.
Please let me know if you see any errors and I'll correct them.
Here are some screenshots to give you an idea of how the rendered manual look
with the new chapter:
You can download a zip-file with the rendered manual here:
https://ufile.io/bf664
Thanks @ericsagnes for the nix expression for the building the manual. You saved
a lot of …

Adds documentation for the external API

---

default.nix
release.nix

This allows users to build hydra using a normal mkDerivation, package overrides, etc.

Move build logic for the core hydra package into its own default.nix.

---

hydra-module.nix
src/lib/Hydra/Plugin/GithubPulls.pm

the json produced by perls encode_json has the keys in a random order, this sorts them, preventing hydra from making a new job every 60 seconds

fix github pulls json to be deterministic

---

src/lib/Hydra/Plugin/GithubStatus.pm

GithubStatus: Don't send a pending status for already-finished builds

---

src/lib/Hydra/Plugin/BitBucketStatus.pm

This plugin will post to the build status system in BitBucket. In order
to use it you need to add to **ExtraConfig**
```
<bitbucket>
username = bitbucket_username
password = bitbucket_password
</bitbucket>
```
You can use an [application password]( https://blog.bitbucket.org/2016/06/06/app-passwords-bitbucket-cloud/) instead of your password. Or you could also use team name and API key.

Add BitBucket plugin

---

src/lib/Hydra/Plugin/GitInput.pm

1. From the hydra configuration file.
The configuration is loaded from the `git-input` block.
Currently only the `timeout` variable is been looked up in the file.
```
<git-input>
timeout = 400
<project:jobset:input-name>
timeout = 400
</project:jobset:input-name>
</git-input>
```
2. As an argument in the input value after the repo url and branch (and after the `deepClone` if is defined)
`timeout=<value>`
The preference on which value is used:
1. input value
2. Inside a block `<project_name:jobset_name:input_name>` in the `<git-input>` block
3. `timeout` inside the `<git-input>` block
4. Default value of 600 seconds. (original hard-coded value)
The code is generalized for more values to be configured, it might be too much for a single value on a single plugin.

Allow to configure the timeout value for the GitInput plugin in different places.

---

src/hydra-queue-runner/queue-monitor.cc

Touchup for fix made in dc5e0b120aac06f1c46bcf0296d14775d72c2354.
Notifications about jobs added shouldn't cause lastBuildId to advance, only to re-scan for possibly missed jobs.
lastBuildId should only advance due to jobs being processed, so take the minimum of the two instead.

queue-monitor: never move lastBuildId forward without processing jobs.

---

release.nix

Removes the dependency from the temporary build dir. Should fix #460

Fix perl search path; avoid reference to build path

---

src/root/static/css/rotated-th.css

Currently if you have multiple rotated table headers in succession, the top part of the `<div>` that holds the content (the link) gets covered up by the next header.

Make all content of rotated table header clickable

---

src/script/hydra-create-user

When creating a Hydra user with the `hydra-create-user` command, you can now provide a SHA1 password hash with the `--password-hash` flag. This is useful for the upcoming work on Fully Declarative Hydra, since the end user should not have to specify plaintext passwords in their `configuration.nix` file.
I've tested this by ensuring that `nix-build release.nix -A tests.api` builds with/without this patch applied:
```diff
diff --git a/release.nix b/release.nix
index 89e7b2a6..b5c5930c 100644
--- a/release.nix
+++ b/release.nix
@@ -218,7 +218,7 @@ rec {
$machine->succeed
-              ( "su - hydra -c \"hydra-create-user root --email-address 'alice\@example.org' --password foobar --role admin\""
+              ( "su - hydra -c \"hydra-create-user root --email-address 'alice\@example.org' …
```

hydra-create-user now has `--password-hash` option

---

release.nix

In order to use `${...}` literally within an indented string we need to prefix it with two single quotes.

release.nix: Fix quoting of ${LOGNAME:-foo}

---

src/lib/Hydra/Controller/JobsetEval.pm
src/lib/Hydra/Helper/CatalystUtils.pm
src/root/user.tt

Frequently users want Hydra access just to restart jobs. However,
prior to this commit the only way to grant that access was by giving
them full Admin access which isn't necessarily what we want to do.
By having a restart-jobs role, we can grant this privilege to users
who are known to the community and want to help, but aren't long-time
members.
~I haven't tested this commit, but as a very novice Perl user, it looks good to me...~ @globin has tested this PR.

Add a restart-jobs role

---

src/lib/Hydra/Plugin/GithubPulls.pm

``nix-store --add`` returns a trailing LF which caused wrong include
paths for the github PR plugin JSON input.

[ Fix #531 ] Trim github pr plugin store paths.

---

src/root/build.tt

Replace `bash <(...)` with `... | bash`
See also: NixOS/nixpkgs#40521

Remove "bashism"

---

src/hydra-eval-jobs/hydra-eval-jobs.cc

The job has been failing since https://hydra.nixos.org/eval/1461286
with the following error:
hydra-eval-jobs.cc:278:17: error: 'evalSettings' was not declared in this scope
evalSettings.restrictEval = true;
^~~~~~~~~~~~
This is likely due to a typo in 0882519 where that line and the
corresponding comment were moved, and `settings` was changed in that
one place to `evalSettings`.
I reproduced the error by running `nix-build release.nix -A
build.x86_64-linux` on my machine, and this small change makes it build.

Fix broken build.x86_64-linux job

---

src/lib/Hydra/Plugin/RunCommand.pm

The current code expects `$self->{config}->{runcommand}` to be an array if it exists at all. This isn't the case when there's precisely one `runcommand`

Allow for precisely one instance of RunCommand plugin

---

src/root/jobset-eval.tt

When I press "n builds omitted" I get back to the first tab of a jobset.
This is extremely counter-intuitive, instead this notice should link to
the currently opened tab.

jobset view: jump back to the proper tab when displaying all failed jobsets

---

src/lib/Hydra/Plugin/DarcsInput.pm

Currently re-using the git cache dir which could cause overlap problems.

Fix darcs input to use darcs-specific SCM cache dir.

---

src/lib/Hydra/Controller/JobsetEval.pm

This endpoint allows efficient retrieval of all the builds in an
evaluation, without making a request for each single build.

feat: add /eval/<id>/builds endpoint

---

configure.ac

This is caused by the autoconf check for `nix-store` which is equivalent
to running this:
```
$ nix-store --timeout 123 -q
```
This would open the pager on a 2.1.1 version of nix.
```
$ nix-store --version
nix-store (Nix) 2.1.1
```
Setting `PAGER` to `cat` ensures the pager doesn't block the
configurePhase.
```
$ PAGER=cat nix-store --timeout 123 -q
```

Stops the pager from blocking at configurePhase

---

src/lib/Hydra/Script/DevServer.pm
src/script/hydra-dev-server

This, in turns allows
- Using --restart for reloading the perl code
- Printing traces on error
* * *
I am invoking [Cunningham's Law](https://meta.wikimedia.org/wiki/Cunningham%27s_Law) here. Following the manual, Appendix A., I couldn't figure out how to make the server handle changes in code. 
With these changes, it becomes more trivial for developers to get in a quick hack/test loop.

Add hydra-dev-server which uses the classic Catalyst server

---

tests/Makefile.am

Hydra has not been deployable from bastion lately due to a build error.
Prior, tests would all fail to build, causing, roughly, the following
error (roughly, because I added some debug log messages :)):
ok 68 - Evaluating jobs/build-products.nix should result in 2 builds
Queue runner stderr: using 4185024512 bytes for the NAR buffer
locking path '/build/source/tests/data/queue-runner/lock'
lock acquired on '/build/source/tests/data/queue-runner/lock.lock'
warning: unknown setting 'max-connection-age'
warning: unknown setting 'max-connections'
dispatcher woken up
dispatcher woken up
dispatcher sleeping for 7674380800s
adding new machine ‘localhost’
dispatcher woken up
checking the queue for builds > 0...
dispatcher sleeping for 7674380800s
sending notification about build 1
loading build …

tests: disable sandbox

---

release.nix

This is a fix for https://discourse.nixos.org/t/why-do-darwin-build-derivations-end-up-on-a-nixos-system/2416/2.
Without this patch running the following on MacOS:
```
nix-build release.nix -A build.x86_64-linux
```
results in the following error during the configuration phase (note that Nix should be configured with a x86_64-linux build machine):
```
building '/nix/store/jb6ca1gmplyb69ayd43z7fb0y9npxd53-hydra-0.1.2581.8b5948f4cf12424c04df67a6eb136c9846fb2cfd.drv' on 'ssh://my-linux-build-machine'...
...
checking whether /nix/store/s6bhdppx66bkgf741vk4d29hgsj1h1zp-hydra-perl-deps/bin/nix-store is recent enough... ./configure: line 16254: /nix/store/s6bhdppx66bkgf741vk4d29hgsj1h1zp-hydra-perl-deps/bin/nix-store: cannot execute binary file: Exec format error
no
configure: error: …
```

Fix Linux build on Darwin

---

src/hydra-eval-jobs/hydra-eval-jobs.cc

Some time ago the data structure for maintainer descriptions in
`nixpkgs` changed from a simple attr set with maintainer emails as
values to an attribute set where the maintainer' nick is associated to
an attribute set with email, GitHub handle and full name.
Hydra can either parse a Nix list or fetches `shortName` from the
associated attribute set (which is used for `meta.licenses` as each
value in it contains a `shortName`). This behavior needs to be
replicated for maintainers to retrieve the emails for `hydra-notify`.
This change is backwards-compatible since `queryMetaStrings` is still
able to understand lists, so old versions of `nixpkgs` or packages using
the old maintainer data structure remain usable.

hydra-eval-jobs: fix maintainer resolution

---

src/lib/Hydra/Controller/Root.pm

Similar to #607. According to the Catalyst[1] docs it's possible to
specify a data structure that is supposed to be serialized when
requesting i.e. a JSON response.
[1] https://metacpan.org/pod/Catalyst::Controller::REST#status_ok

Serialize data as JSON with `Accept: application/json`

---

doc/manual/projects.xml

In the projects documentation, the number `5` comes before the number `4` in the code example annotations. This simply reorders it.

Fix bad ordering in projects documentation.

---

src/hydra-eval-jobs/hydra-eval-jobs.cc

This is because setting only the initial heap size to more than
the default value (or the configured value) will cause all initial evals
until maxHeapSize expands to the given value to abort.
The 1.1 multiplier comes from the the configured defaults on NixOS' hydra,
and from the previous multiplier used before
7876cf677ce086c22faf8909bcec7ac8811f1d39.
* * *
```
$ export GC_INITIAL_HEAP_SIZE=40G
$ .../result/bin/hydra-eval-jobs ...
warning: evaluator_initial_heap_size (42949672960) bigger than evaluator_max_heap_size (1073741824).
evaluator_max_heap_size now set to 47244640256.
```

hydra-eval-jobs: Warn and resets maxHeapSize on bad values

---

src/hydra-queue-runner/hydra-queue-runner.cc
src/lib/Hydra/Plugin/GithubStatus.pm

(cherry picked from commit 1c76ad393669af2f728fd519a050f417319412a6)
This PR adds `useShortContext = 1` as an option to github status that does two things:
1. rename continuous-integration/hydra to ci/hydra
2. remove the PR suffix from the name.
We use this primarily to be able to see full path in github for long job names as well as set protected branches requiring a hydra notification to be present.
It also adds additional debug we found useful to develop this feature.

allow using a shorter context and increase hydra-notify debug

---

src/lib/Hydra/Helper/AddBuilds.pm

(cherry picked from commit 7568b89a1a9da3a58a0cdddc7b5bcea7bb6209d8)
This improves error messages when declarative jobsets are used.

improve the error messages when invalid declarative jobsets are defined

---

src/lib/Hydra/Plugin/GitlabStatus.pm

This plugin expects as inputs to a jobset the following:
- gitlab_status_repo => Name of the repository input pointing to that
status updates should be POST'ed, i.e. the jobset has a git input
"nixexprs": "https://gitlab.example.com/project/nixexprs", in which
case "gitlab_status_repo" would be "nixexprs".
- gitlab_project_id => ID of the project in Gitlab, i.e. in the above
case the ID in gitlab of "nixexprs"
cc @ericson2314 @grahamc 
See https://git.mayflower.de/eso/test-libs/pipelines/4794 and https://hydra-eso-test.yflower.de/jobset/test-libs/pkgs-mr-3 for an example.

Create a gitlab status plugin

---

.gitignore
tests/Makefile.am
tests/set-up.pl

In https://github.com/NixOS/nixpkgs/pull/57677 default postgresql socket directory was changed
to `/run/postgresql`, which doesn't exist (and can't be created) in
Nix build environment. We'll use /tmp as socket dir explicitly then.
Fixes build failure https://hydra.nixos.org/build/91221682
Cc @aszlig @edolstra

tests: change postgresql socket dir to /tmp

---

src/lib/Hydra/Controller/Root.pm
src/sql/hydra.sql
src/sql/upgrade-57.sql

Currently, a full store path has to be provided to search in
builds. This patch permits to search jobs with a output path or
derivation hash.
Usecase: we are building Docker images with Hydra. The tag of the
Docker image is the hash of the image output path. This patch would
allow us to find back the build job from the tag of a running
container image.

Allow to search builds by hash

---

src/lib/Hydra/Controller/Root.pm

By default, search results are limited to 500. This parameter allows a client to reduce this number to speed up response time.
This PR also sets a limit on the `builds` and `buildoutputs` results as it is implemented for job results.

hydra-server: add limit parameter on search path 

---

release.nix

The test was failing with:
machine# Can't locate LWP/UserAgent.pm in @INC (you may need to install the LWP::UserAgent module)...

test.api: use Hydra perl dependencies to run `api-test.pl`

---

hydra-module.nix
src/sql/hydra.sql
src/sql/upgrade-57.sql

The creation of the `pg_trgm` extension needs superuser power. So,
this patch makes the extension creation in the Hydra NixOS module when
a local database is used.
If it is not possible to create this extension (remote database for
instance with nosuperuser), the creation of the `pg_trgm` index is
skipped (this index speedup queries on builds.drvpath) and warnings
are emitted:
initialising the Hydra database schema...
WARNING:  Can not create extension pg_trgm: permission denied to create extension "pg_trgm"
WARNING:  HINT: Temporary provide superuser role to your Hydra Postgresql user and run the script src/sql/upgrade-57.sql
WARNING:  The pg_trgm index on builds.drvpath has been skipped (slower complex queries on builds.drvpath)
This allows to keep smooth migrations: the migration …

Create `pg_trgm` extension in the NixOS module

---

release.nix
src/lib/Hydra/Plugin/InfluxDBNotification.pm
tests/setup-notifications-jobset.pl

This adds a `InfluxDBNotification` plugin which is configured as:
```
<influxdb>
url = http://127.0.0.1:8086
db = hydra
</influxdb>
```
which will write a notification for every finished job to the configured database in InfluxDB looking like: 
```
hydra_build_status,cached=false,job=job,jobset=default,project=sample,repo=default,result=success,status=success,system=x86_64-linux build_id="1",build_status=0i,closure_size=584i,duration=0i,main_build_id="1",queued=0i,size=168i 1564156212
```

Added the InfluxDBNotification plugin including a NixOS test

---

hydra-module.nix
src/hydra-queue-runner/builder.cc
src/hydra-queue-runner/hydra-queue-runner.cc
src/hydra-queue-runner/queue-monitor.cc
src/hydra-queue-runner/state.hh
src/lib/Hydra/Controller/API.pm
src/lib/Hydra/Controller/JobsetEval.pm
src/lib/Hydra/Helper/CatalystUtils.pm
src/lib/Hydra/Plugin.pm
src/lib/Hydra/Plugin/BitBucketStatus.pm
src/lib/Hydra/Plugin/CircleCINotification.pm
src/lib/Hydra/Plugin/CoverityScan.pm
src/lib/Hydra/Plugin/EmailNotification.pm
src/lib/Hydra/Plugin/GithubStatus.pm
src/lib/Hydra/Plugin/GitlabStatus.pm
src/lib/Hydra/Plugin/HipChatNotification.pm
src/lib/Hydra/Plugin/InfluxDBNotification.pm
src/lib/Hydra/Plugin/RunCommand.pm
src/lib/Hydra/Plugin/S3Backup.pm
src/lib/Hydra/Plugin/SlackNotification.pm
src/script/hydra-eval-jobset
src/script/hydra-notify

`hydra-notify` is now a daemon that receives events from `hydra-queue-runner` by listening to PostgreSQL notifications. This makes it a lot more efficient: not starting a `hydra-notify` process for each event avoids the ~1s startup time loading all the plugins. Also, it allows future plugins to be written in any language as long as they can listen to PostgreSQL notifications, and to run on different machines from the queue runner.
The PostgreSQL notifications are:
* `step_started`
* `step_finished`
* `build_started`
* `build_finished`
* `eval_started`
* `eval_failed`
* `eval_cached`
* `eval_added`

Turn hydra-notify into a daemon

---

src/lib/Hydra/Controller/API.pm

This adds the following (pre-existing) attributes to the jobset response:
- nrtotal
- lastcheckedtime
- starttime
- checkinterval
- triggertime
- fetcherrormsg
- errortime
Note that this is identical to #664 but omits `errormsg`. The error message could potentially become arbitrarily long so it is preferable to not deliver it by default.

Extend the jobset API response

---

release.nix

This removes a supper annoying set of messages that polute the logs:
Aug 30 09:00:30 xxx.compute.internal hydra-server[957]: Trouble trying to detect your terminal size, looking at $ENV{COLUMNS}
Aug 30 09:00:30 xxx.compute.internal hydra-server[957]: Term::Size::Any is not installed, can't autodetect terminal column width

Add Term::Size::Any

---

hydra-module.nix

This should fix #430.
We should set `buildMachinesFiles` to `[ "/etc/nix/machines" ]`only when `nix.buildMachines` is set to a non-empty list because that [causes](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/nix-daemon.nix#L341) that file to be generated. 
This should also be applied to [<nixpkgs/nixos/modules/services/continuous-integration/hydra/default.nix>](
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/continuous-integration/hydra/default.nix#L169).

Only set buildMachinesFiles when nix.buildMachines is defined

---

src/lib/Hydra/Controller/Build.pm
src/lib/Hydra/Controller/JobsetEval.pm
src/lib/Hydra/Helper/CatalystUtils.pm
src/root/user.tt

This adds the `cancel-build` & `bump-to-front` roles. The idea is to provide more granular access to hydra.nixos.org.
I tested both on a local hydra instance and so far it works as expected.
cc @grahamc

Add `cancel-build` & `bump-to-front` roles

---

src/script/hydra-send-stats

In 29468995040ae21e0e1c14c1bdbb16ccb514caa8 these metrics got removed
due to refactoring of how notifications work.

hydra-send-stats: Cleanup removed metrics

---

src/lib/Hydra/Controller/Job.pm

Export the most recent stop time and exit status in
a prometheus-friendly format.
```
hydra_job_completion_time{project="nixpkgs",jobset="trunk",job="unstable",nixname="nixpkgs-20.03pre206075.d68c70f1bbb"} 1576853952
hydra_job_failed{project="nixpkgs",jobset="trunk",job="unstable",nixname="nixpkgs-20.03pre206075.d68c70f1bbb"} 1
```
http://147.75.75.222:3000/job/nixpkgs/trunk/unstable/prometheus

job: create a prometheus endpoint

---

src/hydra-evaluator/hydra-evaluator.cc
src/hydra-queue-runner/hydra-queue-runner.cc
src/libhydra/db.hh

Building on macOS with the latest nixpkgs master and NixOS/nixpkgs#77147
fails.  It seems some `std::experimental` (optional for instance) are
not available as `experimental`, but are in `std`.  Also `toJSON` is
missing for `atomic< unsigned long long >`.

Fixes for macOS

---

src/root/build.tt

Remove the "log diff" buttons because they're referencing the removed `logdiff` API.
This API was removed in 4d1816b1529e4877f9527f039facbe9953c187bd.
Fixes #409.

Remove the "log diff" buttons

---

src/lib/Hydra/Schema/JobsetEvals.pm
src/lib/Hydra/Schema/Jobsets.pm
src/sql/hydra.sql
src/sql/upgrade-58.sql

hydra.nixos.org is already running this rev, and it should be safe to
apply to everyone else. If we make changes to this migration, we'll
need to write another migration anyway.
This is needed so the migrations for #710 apply to hydra.nixos.org too.

Copy the flake migration from the flake branch

---

src/lib/Hydra/Schema/Builds.pm
src/lib/Hydra/Schema/Jobs.pm
src/lib/Hydra/Schema/Jobsets.pm
src/script/Makefile.am
src/script/hydra-backfill-ids
src/script/hydra-eval-jobset
src/script/hydra-init
src/sql/hydra.sql
src/sql/upgrade-59.sql
src/sql/upgrade-60.sql
src/sql/upgrade-61.sql

The first half of #710, adding nullable jobset_id fields and populating them.
Currently marking this as a draft, here is my personal to-do list before merging:

jobset_id, #710 Part 1

---

src/lib/Hydra/Controller/Build.pm
src/lib/Hydra/Helper/AddBuilds.pm
src/lib/Hydra/Helper/Nix.pm
src/script/hydra-eval-jobset

I briefly looked for a Nix-1 interface to do this, but readNixFile has always been implemented using nix cat-file.

Fix declarative jobsets due to `nix` command being hidden

---

src/hydra-evaluator/hydra-evaluator.cc
src/lib/Hydra/Controller/Jobset.pm
src/root/edit-jobset.tt
src/root/jobset.tt
src/sql/hydra.sql

In the past, jobsets which are automatically evaluated are evaluated
regularly, on a schedule. This schedule means a new evaluation is
created every checkInterval seconds (assuming something changed.)
This model works well for architectures where our build farm can
easily keep up with demand.
This commit adds a new type of evaluation, called ONE_AT_A_TIME, which
only schedules a new evaluation if the previous evaluation of the
jobset has no unfinished builds.
This model of evaluation lets us have 'low-tier' architectures.
For example, we could now have a jobset for ARMv7l builds, where
the buildfarm only has a single, underpowered ARMv7l builder.
Configuring that jobset as ONE_AT_A_TIME will create an evaluation
and then won't schedule another evaluation until every job of
the existing …

 hydra-evaluator: add a 'ONE_AT_A_TIME' evaluator style

---

src/root/common.tt

When I browse failed builds in a jobset-eval on Hydra, I regularly
mistake actual build-failures with temporary issues like timeouts (that
probably disappear at the next eval).
To prevent this kind of issue, I figured that using the stopsign-svg for
builds with timeouts or exceeded log-limits is a reasonable choice for
the following reasons:
* A user can now distinguish between actual build-errors (like
compilation-failures or oversized outputs) and (usually) temporary issues
(like a bloated log or a timeout).
* The stopsign is also used for aborted jobs that are shown in a
different tab and can't be confused with timeouts for that reason.

Use the stopsign as icon for timeouts and exceeded log-limits

---

src/hydra-queue-runner/builder.cc
src/hydra-queue-runner/dispatcher.cc
src/hydra-queue-runner/hydra-queue-runner.cc
src/hydra-queue-runner/state.hh
src/root/common.tt
src/script/hydra-send-stats

If we don't see machine that supports a build step for `max_unsupported_time` seconds, the step is aborted. The default is 0, which is appropriate for Hydra installations that don't provision missing machines dynamically.

 Abort unsupported build steps

---

src/hydra-eval-jobs/hydra-eval-jobs.cc

Otherwise, errors will not be shown to end-users, which makes debugging
long evals pretty much impossible.
Fixes #728
* * *
**Note**: I'm still testing this change, but want to make it public ASAP so I can be told what I did wrong (and why).

hydra-eval-jobs: Mirror eval errors in STDERR

---

src/hydra-queue-runner/hydra-queue-runner.cc

In `monitorMachinesFile` sleep 5s after handling an exception instead of immediately calling `readMachinesFiles` again which could immediately throw another exception again.

hydra-queue-runner: sleep 5s after handling an exception

---

src/root/build.tt

`nrMembers` is undefined and it should have clearly be `nrConstituents` which is calculated just before.
Fixes #693.
CC @nmattia.

Fix printing aggregate status

---

src/lib/Hydra/Controller/API.pm

Fixes logged messages:
{date} {hostname} hydra-server[PID]: Use of uninitialized value in string eq at /nix/store/.../libexec/hydra/lib/Hydra/Controller/API.pm line 79 <$read> line 383.

Handle case where jobset has no defined errormsg for api/jobsets

---

src/hydra-queue-runner/hydra-queue-runner.cc

`hydra-notify` [splits the payload on tabs](https://github.com/NixOS/hydra/blob/4cabb37ebdeade1435ad8ebf1913cdd603b9c452/src/script/hydra-notify#L105) so we shouldn't separate the IDs with spaces.

Separate the build IDs in the build_finished payload with tabs

---

.gitignore
doc/dev-notes.txt
doc/manual/projects.xml
flake.nix
src/lib/Hydra/Controller/API.pm
src/lib/Hydra/Controller/Admin.pm
src/lib/Hydra/Controller/Build.pm
src/lib/Hydra/Controller/Jobset.pm
src/lib/Hydra/Controller/JobsetEval.pm
src/lib/Hydra/Controller/Project.pm
src/lib/Hydra/Controller/Release.pm
src/lib/Hydra/Controller/User.pm
src/lib/Hydra/Helper/AddBuilds.pm
src/lib/Hydra/Helper/Nix.pm
src/lib/Hydra/Model/DB.pm
src/lib/Hydra/Plugin/BazaarInput.pm
src/lib/Hydra/Plugin/DarcsInput.pm
src/lib/Hydra/Plugin/GitInput.pm
src/lib/Hydra/Plugin/MercurialInput.pm
src/lib/Hydra/Plugin/PathInput.pm
src/lib/Hydra/Plugin/SubversionInput.pm
src/script/hydra-create-user
src/script/hydra-eval-jobset
src/script/hydra-init
src/sql/hydra.sql
tests/Makefile.am

SQLite isn't officially supported for a while. Since it's still used by default, it can lead to confusion by end-users.

Get rid of dependency to SQLite

---

src/lib/Hydra/Plugin/SoTest.pm

https://opensource.sotest.io/
https://docs.sotest.io/
---
A plugin for submitting jobs to a SoTest controller, which manages physical hardware tests.
I would prefer not to declare the credentials in `services.hydra.extraConfig`, is there a method for passing configuration while bypassing the Nix store?

Add SoTest plugin

---

README.md
examples/hello.nix

This adds steps explaining how to create a minimal project and jobset. 
I understand this is beginning to overlap with the scope of a manual so I won't extend the README any further in this regard, but i really wanted the README to get users at least **this** far -- also to demonstrate that this isn't actually very complicated at all.

Extend Setup Information

---

default.nix
shell.nix

Add a comment to default.nix and shell.nix briefly outlining what
flake-compat/default.nix does.
Since i haven't dealt much with flakes before i wasn't aware of the flake-compat repository and what it does and that might be the case for others as well. Doesn't hurt to add a little comment :)

Add comment about edolstra/flake-compat

---

src/hydra-queue-runner/build-remote.cc

Since the recent Hydra upgrade in nixpkgs, I have noticed that builds that are supposed to be running on localhost are actually getting distributed to other machines configured in `/etc/nix/machines`. If the build fails on the remote machine, it is marked as aborted.
I suspect this is caused by a change in Nix, rather than in Hydra, but I couldn't identify a commit that is to blame. It does not seem to happen for builds that Hydra intentionally runs on remote machines, even if those remote machines have builders configured in `/etc/nix/machines`. This may be due to implementation differences between the `cmdBuildPaths` `nix-store --serve` command (used for localhost builds) and the `cmdBuildDerivation` command (used for remote builds).
Note that I am still running `hydra-migration` …

Don't distribute localhost builds to other builders

---

src/lib/Hydra/Plugin/GithubRefs.pm

This plugin is a counterpart to GithubPulls plugin. Instead of fetching pull
requests, it will fetch all references (branches and tags) that start with a
particular prefix.
The plugin is a copy of GithubPulls plugin with appropriate changes to call the
right API and parse the config matching the need.

Add GithubRefs plugin

---

flake.nix

Since Perl-based NixOS tests will be deprecated in nixpkgs 20.09, this
change migrates all tests to the new Python-based NixOS tests.

Convert all tests to the Python DSL

---

src/lib/Hydra/Plugin/GitInput.pm

The previous code converted option values to ints when the value contained a digit somewhere. This is too eager since it also converts strings like `release-0.2` to an int which should not happen.
We now only convert to int when the value is an integer.

GitInput: only convert integer option values to int

---

src/lib/Hydra/Controller/Job.pm
src/lib/Hydra/Controller/Jobset.pm
src/lib/Hydra/Schema/Builds.pm

This was clearly an error in the original part-2 of the diff, and
specifically breaks when two projects have a jobset of the same name.

schema/Builds: use jobset_id instead of jobset name matches

---

README.md

The correct filename is `hydra-api.yml` not `hydra.yml`.

Correct the link to hydra-api.yml file

---

src/lib/Hydra/Helper/AddBuilds.pm
src/sql/upgrade-66.sql

The current implementation will pass all values to `create_or_update` method. The
missing values will end up as `undef` (or `NULL`) when assigned to `%update`.
Thus, for columns that are NOT NULL, when, for example, flakes are not used,
will result in a horrible:
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed:
ERROR:  null value in column "type" violates not-null constraint
DETAIL:  Failing row contains (.jobsets, 118, hydra, hydra jobsets, src, hydra/jobsets.nix, null,
null, null, 1589536378, 1, 0, 0, , 3, 30, 100, null, null, 1589536379, null, null). [for Statement
"UPDATE jobsets SET checkinterval = ?, description = ?, enableemail = ?, nixexprinput = ?,
nixexprpath = ?, type = ? WHERE ( ( name = ? AND project = ? ) )" with ParamValues: 1='30', …

Fix declarative jobset missing type value

---

src/root/jobset.tt

The original code would return standard "Please come back later" page when there
are only fetch errors on a newly setup declarative project. The problem is that
there are two types of errors: standard errors and fetch errors. Each is
acompanied by a corresponding field for time of occurence. Standard errors use
'errortime', while fetch errors have 'lastchecktime' set to the time of the
error. Unfortunately, jobset.tt file was only using 'errortime' for displaying
the time. This would result in the following errors in logs:
Couldn't render template "date error - bad time/date string:  expects 'h:m:s d:m:y'  got: ''
This change includes using 'lastchecktime' when rendering the error times.

Render the jobset page correctly when there are fetch errors

---

Procfile
foreman/start-notify.sh

I came across https://github.com/NixOS/hydra/issues/751 and realized
that hydra-notify is responsible for creating the additional jobsets in
a declarative file. My declarative testing works in dev now.

Add hydra-notify to devshell

---

src/lib/Hydra/Helper/AddBuilds.pm
src/lib/Hydra/Helper/Nix.pm
src/script/hydra-notify
src/script/hydra-send-stats

Taken from `Perl::Critic`:
A common idiom in perl for dealing with possible errors is to use `eval`
followed by a check of `$@`/`$EVAL_ERROR`:
eval {
...
};
if ($EVAL_ERROR) {
...
}
There's a problem with this: the value of `$EVAL_ERROR` (`$@`) can change
between the end of the `eval` and the `if` statement. The issue are object
destructors:
package Foo;
...
sub DESTROY {
...
eval { ... };
...
}
package main;
eval {
my $foo = Foo->new();
...
};
if ($EVAL_ERROR) {
...
}
Assuming there are no other references to `$foo` created, when the
`eval` block in `main` is exited, `Foo::DESTROY()` will be invoked,
regardless of whether the `eval` finished normally or not. If the `eval`
in `main` fails, but the `eval` in `Foo::DESTROY()` succeeds, then
`$EVAL_ERROR` will be empty by the time that the …

Improve handling of Perl's block eval errors

---

src/script/hydra-eval-jobset

When deploying Hydra different than hydra.nixos.org one may encounter a problem
as building any job that uses IFD fails with:
```
May 22 19:41:07 hydra hydra-evaluator[6960]: error: "attempted to realize '/nix/store/1jm02mfiv58rpy8zrx95cpqxzsp64ssh-source.drv' during evaluation but 'allow-import-from-derivation' is false"
May 22 19:41:07 hydra hydra-evaluator[6960]: error: "attempted to realize '/nix/store/av3jr8ix4qcadq2wm3y3hplvxwzlhl4y-source.drv' during evaluation but 'allow-import-from-derivation' is false"
May 22 19:41:07 hydra hydra-evaluator[6960]: error: "attempted to realize
'/nix/store/2jm02mfiv58rpy8zrx95cpqxzsp64ssh-source.drv' during evaluation but
'allow-import-from-derivation' is false"
```
The recent change enforced passing `--no-allow-import-from-derivation`
to …

Make --no-allow-import-from-derivation configurable in hydra-eval-jobset

---

src/script/hydra-notify

`build_finished` Postgres event will never be fired for the dependent builds.
For example, on our Hydra, the following query always returns increasing
numbers, even though all notifications have been delivered:
```
hydra=> select count(1) from builds where notificationpendingsince is not null;
count
-------
4583
(1 row)
```
Thus, we have to iterate over all dependent builds and mark their
`notificationpendingsince` as `null`, otherwise they will pile up until
the next restart of hydra-notify, when they will get delivered.

Fix: Set notificationpendingsince for dependent builds

---

src/script/hydra-send-stats

cc @edolstra @knl 
----
Introduced in f79810bac1a3a45abe488e975b06bd867105e26e.

Fix syntax error in `hydra-send-stats`

---

src/script/hydra-init
src/sql/Makefile.am
src/sql/update-dbix-harness.sh

As of https://github.com/NixOS/hydra/pull/737 (removal of sqlite
dependency), the only supported database is Postgresql.
This change removes all references to hydra-postgresql.sql file. This
file is generated using a cpp on hydra.sql, but doesn't differ from
hydra.sql at all.

Remove references to hydra-postgresql.sql

---

flake.nix
src/lib/Hydra/Plugin/PathInput.pm
tests/api-test.pl

PathInput plugin keeps a cache of path evaluations. This cache is simple, and
path is not checked more than once every N seconds, where N=30. The caching is
there to avoid expensive calls to `nix-store --add`.
This change makes the validity period configurable. The main use case is
`api-test.pl` which was implemented wrong for a while, as the invocation of
`hydra-eval-jobset` would return the previous evaluation, claiming there are no
changes. The test has been fixed to check better for a new evaluation.

Make PathInput plugin cache validity configurable

---

hydra-module.nix

This was slated to be removed with Nix 16.03. We're now in 20.03, so
it's good to clean that up a bit.

Remove SSL_CERT_FILE

---

src/lib/Hydra/Plugin/InfluxDBNotification.pm

This should help us discern machines in environments with multiple Hydra deployments.

Add host tag to InfluxDB metrics

---

src/lib/Hydra/Helper/AddBuilds.pm

`emailresponsible` has a default of 0 in the DB so let's not require this field in the API.

updateDeclarativeJobset: only set the emailresponsible column when defined

---

doc/manual/installation.xml
flake.nix
src/lib/Hydra.pm
src/lib/Hydra/Controller/User.pm

This is picking up the work from @ajs124 in #684.
The main difference to the previous PR is that I started writing tests for it (while I was trying to figure out if it is working). That work required adding the missing perl packages which I'm also adding to NixPkgs in https://github.com/NixOS/nixpkgs/pull/97673. For the meantime they should probably be kept in here until NixOS 21.03 is released.
As written in the original PR this still has the hard coded `hydra_` prefix for all the roles that are currently supported by hydra. IMO extending that is out of scope for an initial implementation. If someone really needs different names and/or has multiple hydra setups with different permissions for the same person they can still have a different OU's in their LDAP and filter accordingly.

LDAP support continued (with missing packages & tests)

---

flake.nix
src/lib/Hydra/Controller/User.pm

This is follow-up to #805 in which I broken non-LDAP login by accident. This also fixes the test that got broken while massaging all the formatting and whitespaces in the LDAP test.
I did run all the tests locally but would very much welcome someone else to execute them just to be sure. cc @ajs124  @grahamc

ldap: only try the LDAP realm when it is configured

---

src/root/reproduce.tt

The reproduce script would fail for me, because it passed revCount as
a string to nix-build, which would then fail to subtract from it.

reproduce bash script must supply revCount as int

---

src/script/hydra-eval-jobset

With the current implementation, if ANY hash was found inside the decl
spec, the spec would be treated as static. This is problematic since
`inputs` is a hash and hence any configuration would be handled as a
static one.
This fixes the code to match the documentation and only switch to static
processing when ALL values are hashes.
cc @grahamc @edolstra

Fix non-static declarative jobsets

---

flake.lock
flake.nix

We should lead with good example and when users copy code from this repo
it should not incentivize them to use plain text passwords.
I also had to update to nixos-20.09-small as that allows us to use the pw-sha2 ldap module in the test (they were not being built in the 20.03 version of the expression).
The 20.09 upgrade requires us to use breezy and not `bazaar` as bazaar had been deprecated.

ldap: Use hashed passwords in the test

---

flake.lock
src/hydra-eval-jobs/hydra-eval-jobs.cc
src/hydra-queue-runner/build-remote.cc
src/hydra-queue-runner/build-result.cc
src/hydra-queue-runner/builder.cc
src/hydra-queue-runner/hydra-queue-runner.cc
src/hydra-queue-runner/queue-monitor.cc

This PR contains an automatic `flake.lock` update (2394140) and updates the code in `hydra-queue-runner` to compile again (
9cc76f6). The details can be found in the commit messages.
cc @edolstra @grahamc @ericson2314 @lheckemann

Fix build against latest Nix master

---

src/lib/Hydra/Plugin/GithubStatus.pm

These make the hydra-queue-runner logs very noisy even when not using the GitlabStatus plugin.
Also, they shouldn't be necessary except when developing the plugin itself and should have been removed before release.

Remove Debug prints from GitLabStatus.pm

---

hydra-api.yaml
src/lib/Hydra/Controller/Job.pm

Closes #163
Here is an example using a hydra server that I host:
generated from this url: `https://img.shields.io/endpoint?url=https%3A%2F%2Fhydra.technicie.nl%2Fjob%2Fconcrexit%2Fmaster%2Fconcrexit-release%2Fshield`

Add endpoint to generate a shields.io badge

---

src/sql/hydra.sql
src/sql/upgrade-69.sql

Looking at AWS' Performance Insights for a Hydra instance, I found
the hydra-queue-runner's query:
select id, buildStatus, releaseName, closureSize, size
from Builds b
join BuildOutputs o on b.id = o.build
where
finished = ?
and (buildStatus = ? or buildStatus = ?)
and path = $1
was the slowest query by at least 10x. Running an explain on this
showed why:
hydra=> explain select id, buildStatus, releaseName, closureSize, size
from Builds b join BuildOutputs o on b.id = o.build where
finished = 1 and (buildStatus = 0 or buildStatus = 6) and
path = '/nix/store/s93khs2dncf2cy273mbyr4fb4ns3db20-MIDIVisualizer-5.1';
QUERY PLAN
------------------------------------------------------------------------
Gather  (cost=1000.43..33718.98 rows=2 width=56)
Workers Planned: 2
->  Nested Loop …

BuildOutputs: index path with HASH

---

.gitignore
src/lib/Hydra/Schema/JobsetEvals.pm
src/root/common.tt
src/root/jobset-eval.tt
src/script/hydra-eval-jobset
src/sql/hydra.sql
src/sql/upgrade-70.sql
tests/set-up.pl

Today, Hydra records evaluation errors in the Jobsets table only. When a new evaluation happens, the old log is lost. This can be pretty annoying if you're trying to debug an issue and a new evaluation finishes while you're hunting.
This PR adds evaluation errors to the jobsetevals table and writes the evaluation log to it in addition to storing the latest evaluation error to jobsets.
The included migration copies the jobset's evaluation error output to the latest jobsetevals record for that jobset. It shouldn't take long to execute this migration: it takes a minute or so to run against hydra's production dataset, on a significantly underpowered server.
It looks like this:

JobsetEvals: record evaluation errors

---

src/lib/Hydra/Schema/Builds.pm
src/lib/Hydra/Schema/JobsetEvals.pm
src/lib/Hydra/Schema/Jobsets.pm
src/lib/Hydra/Schema/Projects.pm
src/root/build.tt
src/root/reproduce.tt
src/script/hydra-eval-jobset
src/sql/hydra.sql
src/sql/upgrade-71.sql

I meant to open this as a draft.
Duplicating this data on every record of the builds table cost
approximately 4G of duplication.
Note that the database migration included took about 4h45m on an
untuned server which uses very slow rotational disks in a RAID5 setup,
with not a lot of RAM. I imagine in production it might take an hour
or two, but not 4. If this should become a chunked migration, I can do
that.
Note: Because of the question about chunked migrations, I have NOT
YET tested this migration thoroughly enough for merge.

Normalize nixexpr{input,path} from builds to jobsetevals.

---

src/hydra-evaluator/hydra-evaluator.cc
src/lib/Hydra/Controller/Admin.pm
src/lib/Hydra/Controller/JobsetEval.pm
src/lib/Hydra/Helper/Nix.pm
src/lib/Hydra/Schema/JobsetEvals.pm
src/lib/Hydra/Schema/Jobsets.pm
src/lib/Hydra/Schema/Projects.pm
src/root/common.tt
src/script/hydra-dev-server
src/script/hydra-eval-jobset
src/sql/hydra.sql
src/sql/update-dbix-harness.sh
src/sql/upgrade-72.sql

Instead of referring to the jobset by its project's name and the jobset's name, refer to it by a jobset_id.
* I added a little in-line notes about how to write database migrations.
* I fixed a problem where the `make` for updating the schema libraries would succeed even if the SQL was invalid.
* I fixed a minor problem where hydra-dev-server was buffering output to stderr/stdout
* The C++ in hydra-evaluator feels a bit heavy on boilerplate, but it seemed like a good way to go. I'm open to doing something different. I wrote this in a few separate commits to make it easier for me to grok.
* The perl patches were surprisingly short and easy. I clicked around, ran the tests, ran some evaluations and builds

Jobset -> JobsetEvals by JobsetEvals.jobset_id

---

src/lib/Hydra/Controller/Root.pm

This search query is pretty heavy. Defaulting to 500 has caused
Hydra's web UI to appear to be down. Since 500 can take it down, users
probably shouldn't be allowed t ask for that many.

search: limit results to 50, default to 10

---

src/lib/Hydra/Helper/Nix.pm
src/lib/Hydra/Schema/EvaluationErrors.pm
src/lib/Hydra/Schema/JobsetEvals.pm
src/root/common.tt
src/root/jobset-eval.tt
src/script/hydra-eval-jobset
src/sql/hydra.sql
src/sql/update-dbix.pl
src/sql/upgrade-73.sql

BIx likes to eagerly select all columns without a way to really tell
it so. Therefore, this splits this one large column in to its own
table.
I'd also like to make "jobsets" use this table too, but that is on hold
to stop the bleeding caused by the extreme amount of traffic this is
causing.
I checked this by running an evaluation locally and ensuring the evaluation's errors were recorded. I also checked by fetching a recent copy of prod's database and running the migration and verifying the evaluation data was correctly migrated.

Move evaluation errors from evaluations to EvaluationErrors, a new table

---

src/lib/Hydra/Helper/AddBuilds.pm

The database has these constraints (or improved ones with #856):
```sql
check ((type = 0) = (nixExprInput is not null and nixExprPath is not null)),
check ((type = 1) = (flake is not null)),
```
which prevented switching to flakes in a declarative jobspec, since the
`nixexpr{path,input}` fields were not nulled in such an update.
This commit explicitly `null`'s the fields that are needed for the specific `type`.
I have verified that this change allows switching a declarative jobset from non-flakes to flakes.
Ping @grahamc, he helped writing this fix

Fix transition from declarative non-flake to flake jobset

---

src/lib/Hydra/Controller/JobsetEval.pm

Going from an eval to a project now requires hopping through the jobset
Reported by @andir.

JobsetEvals: fixup permission references

---

src/sql/hydra.sql
src/sql/upgrade-74.sql

The current check happening in jobsets is incorrect.
The wanted constraint is stated as follow :
- If type is 0 (legacy), then the flake field should be null, and both nixExprInput and nixExprPath should be non-null
- If type is 1 (flake), then the flake field should be non-null, and both nixExprInput and nixExprPath should be null
The current version will not catch (i.e. it will accept) situations
where you have for instance :
```
type = 1, nixExprPath null, nixExprInput non-null, flake non-null
```
This commit fixes that.
I split(ted) that into two constraints, to make it more readable and
easier to extend if a new type appears in the future.
The complete query could be instead :
```
( type = 0
AND nixExprInput IS NOT NULL AND nixExprPath IS NOT NULL AND flake IS NULL )
OR ( type = 1 …
```

Fix check in jobsets

---

src/hydra-queue-runner/build-remote.cc

The queue runner used to special-case `localhost` as a remote builder: Rather than using the normal remote-build (using the `cmdBuildDerivation` command), it was using the (generally less efficient, except when running against localhost) `cmdBuildPaths` command because the latter didn't require a privileged Nix user (so made testing easier − allowing to run hydra in a container in particular).
However:
1. this means that the build loop can follow two discint code paths depending on the setup, the irony being that the most commonly used one in production (the “non-localhost” case) isn't the one used in the testsuite (because all the tests run against a local store);
2. It turns out that the “localhost” version is buggy in relatively obvious ways − in particular a failure in a fixed-output …

Remove the `sendDerivation` logic from the builder

---

src/script/hydra-notify
tests/jobs/runcommand.nix
tests/lib/Setup.pm
tests/plugins/runcommand.t

Validate its behavior in general. A bunch of people depend on this pretty heavily, so I think it makes sense to have it well tested.
This adds support for running notifications during a test, adding a `--queued-only` flag to the notifier which processes queued notifications and then exits.
This also adds the ability to specify arbitrary Hydra configuration for a given test.

Test RunCommand's behavior

---

tests/build-products.t
tests/evaluate-basic.t
tests/evaluate-dependent-jobsets.t
tests/input-types/bzr-checkout.t
tests/input-types/bzr.t
tests/input-types/darcs.t
tests/input-types/deepgit.t
tests/input-types/git-rev.t
tests/input-types/git.t
tests/input-types/hg.t
tests/input-types/svn-checkout.t
tests/input-types/svn.t
tests/lib/Setup.pm
tests/lib/TestScmInput.pm
tests/plugins/runcommand.t

This way we can return more values without breaking callers.
---
Also add `jobsdir` and `testdir` to the ctx hash.

tests: replace the flat list of contexts with a hash

---

src/root/reproduce.tt

A reproduce script includes a logline that may resemble:
> using these flags: --arg nixpkgs { outPath = /tmp/build-137689173/nixpkgs/source; rev = "fdc872fa200a32456f12cc849d33b1fdbd6a933c"; shortRev = "fdc872f"; revCount = 273100; } -I nixpkgs=/tmp/build-137689173/nixpkgs/source --arg officialRelease false --option extra-binary-caches https://hydra.nixos.org/ --option system x86_64-linux /tmp/build-137689173/nixpkgs/source/pkgs/top-level/release.nix -A 
These are passed along to nix-build and that's fine and dandy, but you can't just copy-paste this as is, as the `{}` introduces a syntax error and the value accompanying `-A` is `''`.
A very naive approach is to just `printf "%q"` the individual args, which makes them safe to copy-paste. Unfortunately, this looks awful due to the liberal …

Make nix-build args copy-pastable via `set -x`

---

doc/manual/src/projects.md
src/script/hydra-eval-jobset

This allows for more generic declarative configurations which can be
shared between projects.

Add the project name to declarative inputs

---

src/script/hydra-eval-jobset

```
Mar 10 16:22:35 hydra-b hydra-evaluator[41419]: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  null value in column "type" violates not-null constraint
Mar 10 16:22:35 hydra-b hydra-evaluator[41419]: DETAIL:  Failing row contains (62358, projectName, 0, null, null, null, hackworthltd, null, , null). [for Statement "INSERT INTO jobsetevalinputs ( altnr, dependency, eval, name, path, revision, sha256hash, type, uri, value) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )" with ParamValues: 1='0', 2=undef, 3='62358', 4='projectName', 5='', 6=undef, 7=undef, 8=undef, 9=undef, 10='hackworthltd'] at /nix/store/cmqblv437mp57yz5lwvkzcqca4ldf3r5-hydra-0.1.20210308.ebf1cd2/bin/.hydra-eval-jobset-wrapped line 793
Mar 10 16:22:35 hydra-b …
```

Fixup #717 "Add the project name to declarative inputs"

---

src/hydra-queue-runner/builder.cc
src/hydra-queue-runner/dispatcher.cc
src/hydra-queue-runner/queue-monitor.cc
src/hydra-queue-runner/state.hh

Previously, the already-done, cached, build ID would never flow through channels which
exited.
This patch tracks the buildOne state as part of State and exits avoids
waiting forever for new work.
The code around buildOnly is a bit rough, making this a bit weird to
implement but since it is only used for testing the value of improving
it on its own is a bit questionable.

hydra-queue-runner: --build-one: correctly handle a cached build

---

src/lib/Hydra/Helper/AttributeSet.pm
src/lib/Hydra/Helper/Escape.pm
src/lib/Hydra/View/NixExprs.pm
t/Controller/Jobset/channel.t
t/Helper/attributeset.t
t/Helper/escape.t
t/jobs/nested-attributes.nix

This is a breaking change. Previously, packages named `packageset.foo`
would be exposed in the fake derivation channel as `packageset-foo`.
Presumably this was done to avoid needing to track attribute sets, and
to avoid the complexity. I think this now correctly handles the
complexity and properly mirrors the input expressions layout.

 Test the fake derivations channel, asserting nested packages are properly represented.

---

doc/manual/src/projects.md
flake.nix
src/lib/Hydra/Plugin/GiteaStatus.pm
t/jobs/server.py
t/plugins/gitea.t

This plugin is fairly heavily inspired by the implementations for GitHub and GitLab. It basically checks for the build-state of a jobset evaluation and then marks the commit as `failed`/`succeeded` using the REST API.
A simple example how to configure/use is added to the manual, also it's verified using a VM test in `flake.nix`.
cc @grahamc @cole-h

Add `GiteaStatus`-Plugin

---

src/root/user.tt

A user thought they had admin access because "admin" appeared in their list of roles. They had *no* special roles, so they didn't know the deselected ones were ones they didn't have.
This PR (built on top of #677; will rebase when that merges) changes the multi select to checkboxes. This change made the "admin" checkbox close visually and distance closer to the "public dashboard" tickbox. A bit scary. So, this PR also made the role checkboxes more separate.
Thanks to @samueldr for help on this.
For admins:
For regular users:

User Roles: make checkboxes

---

src/lib/Hydra/Controller/Root.pm

Fix login if Hydra runs behind HTTP proxy with sub-path location

---

src/lib/Hydra/Plugin/PathInput.pm

The PathInput input for local paths was previously enhanced to allow
URLs for which it would use a nix-prefetch-url operation.  This change
updates the prompt for the declarative input type to indicate this
capability.

Update prompt for Local path input to indicate a URL is also valid.

---

src/hydra-queue-runner/build-remote.cc

In Nix the protocol was slightly altered[1] to also contain more
information about realisations. This however wasn't read from the pipe
that was used to read from the store.
After the `cmdBuildDerivation` command which caused this issue, Hydra
will issue a `cmdQueryPathInfos` that tries to read from the remote
store as well. However, there's still left over to read from the
previous command and thus Nix fails to properly allocate the expected
string.
[1] See rev a2b69660a9b326b95d48bd222993c5225bbd5b5f
Fixes #898
cc @regnat @edolstra @grahamc

Fix `std::bad_alloc` errors for remote builds

---

flake.nix
src/lib/Hydra.pm
src/lib/Hydra/Controller/Admin.pm
src/lib/Hydra/Controller/Root.pm
src/lib/Hydra/Controller/User.pm
src/lib/Hydra/Schema/Users.pm
src/script/hydra-create-user
t/Schema/Users.t

New users will have their passwords stored with Argon2id. Existing users that already have unsalted sha1 passwords will have their stored password transparently migrated to Argon2id.
This patch also upgrades the sha1 checking to be constant time, an improvement over Catalyst's default behavior.
Closes #63

Hydra auth: support Argon2, transparently upgrade hashes

---

src/lib/Hydra/Schema/Users.pm
src/script/hydra-create-user
src/script/hydra-init
t/Schema/Users.t
t/scripts/hydra-create-user.t
t/scripts/hydra-init.t

In #915 we transparently upgrade user passwords to Argon2 on login. However, as [wkral mentioned on Discourse,](https://discourse.nixos.org/t/hydra-upgrade-hashes-to-argon2/12497/4?u=grahamc), this leaves the passwords poorly hashed in the database for users who don't log in. They suggested what [OWASP suggests](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#upgrading-legacy-hashes):
> use the existing password hashes as inputs for a more secure algorithm. For example, if the application originally stored passwords as md5($password), this could be easily upgraded to bcrypt(md5($password)). Layering the hashes avoids the need to know the original password; however, it can make the hashes easier to crack. These hashes should be replaced with direct hashes …

Rehash existing sha1 passwords with Argon2

---

src/lib/Hydra/Controller/Project.pm

The checkbox is only enabled if `email_notification = 1` is set in
`hydra.conf`. However, when creating jobset (in contrast to the edit
form), the checkbox is always disabled because the `emailNotification`
parameter in Catalyst's stash was missing.
cc @grahamc

Make it possible to enable email notifications when creating a jobset

---

doc/manual/src/projects.md
flake.nix

The addition of AuthenSASL seems to be necessary to properly
authenticate against an SMTP server. Without this I got errors
such as
error with Hydra::Plugin::EmailNotification=HASH(0x6ad0128)->buildFinished: SMTP auth requires MIME::Base64 and Authen::SASL
cc @grahamc

Add AuthenSASL to perl deps; improve email docs

---

hydra-api.yaml

The PUT API doesn't accept `hidden` (even though the GET API responds with it).
---
See: https://github.com/NixOS/hydra/issues/930.
A better fix would be to unify these, but I'll leave that for another day. Let's just fix the spec file to reflect the current API.

hydra-api: hidden -> visible

---

hydra-api.yaml

The Hydra website allows you to change the name of a Project, so it only makes
sense for the API to expose this functionality as well.

hydra-api: add missing `name` property

---

hydra-api.yaml
src/lib/Hydra/Controller/Jobset.pm
src/lib/Hydra/Controller/User.pm
src/lib/Hydra/Schema/JobsetInputs.pm
src/lib/Hydra/Schema/Jobsets.pm
src/root/edit-jobset.tt
t/Controller/Jobset/http.t

```
$ curl -X 'GET' 'http://0:63333/jobset/test/test11' -H 'accept: application/json' | jq
{
"type": 1,
"description": "test2",
"triggertime": null,
"keepnr": 0,
"hidden": false,
"errormsg": "",
"nixexprinput": "",
"lastcheckedtime": null,
"errortime": null,
"jobsetinputs": {},
"flake": "github:nixos/nix",
"enabled": 2,
"checkinterval": 0,
"fetcherrormsg": "",
"project": "test",
"name": "test11",
"emailoverride": "",
"starttime": null,
"enableemail": false,
"schedulingshares": 100,
"nixexprpath": ""
}
$ curl -X 'GET' 'http://0:63333/jobset/test/asdf' -H 'accept: application/json' | jq
{
"fetcherrormsg": "",
"project": "test",
"name": "asdf",
"enabled": 1,
"checkinterval": 0,
"enableemail": false,
"schedulingshares": 1,
"nixexprpath": "fdsa",
"emailoverride": "",
"starttime": null, …
```

hydra-api: flesh out Jobset, JobsetInput schemas; implement DELETE /jobset/{project-id}/{jobset-id}

---

t/Controller/Jobset/channel.t
t/lib/Setup.pm

Set `dest_store` in the test hydra config, so that the testsuite ensures
that the distinction between the local store and the destination store
is properly taken into account.
Fix #938
This currently causes the `channel.t` test to fail − [this call](https://github.com/NixOS/hydra/blob/019aef3d419b03266f7a137300b54bcfa167350e/t/Controller/Jobset/channel.t#L36) returns a 404.
I'm not sure whether this is an issue with the test or hydra itself (I've no idea how the channels feature works). @grahamc do you have an idea as the author of the test?

Run the tests with a remote dest store

---

hydra-api.yaml
src/lib/Hydra/Controller/Project.pm
src/lib/Hydra/Schema/Projects.pm
src/root/edit-project.tt
t/Controller/projects.t

This makes it possible to create declarative projects via a PUT request, and
also exposes the currently-configured values to GET requests.
---
`decl*` are all nullable -- should these be string columns (where they are `""` if null), or "normal" columns (where they are actual `null`s if null)?

Project: add declfile, decltype, declvalue to API

---

src/lib/Hydra/Plugin/GithubStatus.pm

Also, if the parse fails, don't try to update the GitHub status, as this will eventually cause rate-limiting.

Fix GitHub status update for private flakes.

---

src/root/static/js/common.js

Something in the upgrade of Bootstrap and JQuery broke lazy tab loading.
I don't understand what is providing the tab behavior, how it should
work, or what the correct fix is.
I can tell you that this patch fixes the issue: when loading a tab
with a URL fragment deep-linking to a lazily loaded tab... it now
loads.
Close #959

lazy tabs: trigger the load event

---

src/lib/Hydra/Controller/Project.pm
t/Controller/projects.t

"No longer declarative" as defined by the "Edit project" page is an empty spec
file.
---
Fixes https://github.com/NixOS/hydra/issues/960.
~~TODO: write a test~~

Project: delete the `.jobsets` jobset if project is no longer declarative

---

src/lib/Hydra/Schema/Jobsets.pm

It appears the Jobs table was removed in
8adb433e3b48638f3faaecc61ae5cb63efefff6e, but the Jobsets schema was never
updated to reflect this. This relationship was added in
efa1f1d4fbdc468c61f7403e8709d0295e052c7f, roughly 3 months prior.
Previously, one would see a message similar to the following logged when
deleting a jobset:
17:38:23 hydra-server.1       | DBIx::Class::Relationship::CascadeActions::delete(): Skipping cascade delete on relationship 'jobs' - related resultsource 'Hydra::Schema::Jobs' is not registered with this schema at /home/vin/workspace/vcs/hydra/src/script/../lib/Hydra/Controller/Jobset.pm line 106

Jobsets: remove defunct Jobs relationship

---

src/lib/Hydra/Schema/Projects.pm
t/Controller/projects.t

If the project isn't declarative, who cares about it in the response? After
setting the `declfile` to an empty string, everything related to declarative-
ness is wiped out, anyways.
```
$ curl 'http://0:63333/project/ofborg' -H 'accept: application/json' | jq
{
"hidden": false,
"description": "grahamcofborg automation",
"jobsets": [],
"name": "ofborg",
"owner": "alice",
"displayname": "ofborg",
"enabled": true,
"homepage": "https://github.com/grahamc/ofborg"
}
$ curl 'http://0:63333/project/nixpkgs-declarative' -H 'accept: application/json' | jq
{
"jobsets": [
".jobsets"
],
"description": "Nix Packages collection",
"name": "nixpkgs-declarative",
"owner": "alice",
"homepage": "https://nixos.org/nixpkgs",
"displayname": "Nixpkgs",
"enabled": false,
"declarative": {
"value": …
```

Projects: don't respond with unnecessary declarative field

---

src/lib/Hydra/Controller/Build.pm
src/lib/Hydra/Controller/Jobset.pm
src/lib/Hydra/Controller/Root.pm
src/lib/Hydra/Helper/Nix.pm
t/Controller/Build/evals.t
t/Controller/Jobset/channel.t
t/Controller/Jobset/evals.t
t/Controller/Root/evals.t
t/build-products.t
t/evaluate-basic.t
t/evaluate-dependent-jobsets.t
t/plugins/runcommand.t
t/queue-runner/default-machine-file.t
t/queue-runner/notifications.t

Closes #917 
I broke this when I added `me.` in f1e75c8
I added me. to disambiguate `id`, but:
* eval.id works on the per-build page
* me.id works on the other pages
* Just id works everywhere if I drop:
, prefetch => { evaluationerror => [ ] },
but this causes a query per row to collect the evaluationerror
records later, this becomes significantly slow on non-trivial
datasets.
Using evals->current_source_alias will use the correct alias
whether it is me or eval or something else.

/build/ID/evals: fix after #860

---

flake.nix

Nixpkgs on unstable has removed `stdenv.lib` as they've been warning for a while now. This removes the extra references to it in the flake.nix
I'm not entirely sure if this is right, but I figured it was trivial enough to give a quick try using the GH Editor while I was waiting for a job to finish

flake: stdenv.lib -> lib

---

doc/manual/src/SUMMARY.md
doc/manual/src/jobs.md

From a question matrix:
> wucke13
> Even more noise: where can the timeout be configured for hydra jobs? Couldn't find the term timeout in the manual nor the nixos options

Docs: document derivation attributes

---

doc/manual/src/jobs.md

Followup to https://github.com/NixOS/hydra/pull/979, fixes invalid syntax in the example.

Docs: fixup `maintainers` derivation meta field example

---

src/lib/Hydra/Plugin/GitInput.pm
src/lib/Hydra/Schema/CachedGitInputs.pm
src/sql/hydra.sql
src/sql/upgrade-76.sql

Without this commit, two jobsets using the same repository as input, but different `deepClone` options, end up incorrectly sharing the same "checkout" for a given (`uri`, `branch`, `revision`) tuple.  The presence or absence of `.git` is determined by the jobset execution order.
This patch adds the missing `isDeepClone` boolean to the cache key.
The database upgrade script empties the `CachedGitInputs` table, as we don't know if existing checkouts are deep clones.  Unfortunately, this generally forces rebuilds even for correct `deepClone` checkouts, as the binary contents of `.git` are not deterministic.
Fixes #510

GitInput: Include deepClone option in the cache key

---

src/lib/Hydra/View/TT.pm
src/root/jobset.tt

Show evaluation time in the evaluations overview

---

t/Controller/Jobset/type-constraints.t

Prior to https://github.com/NixOS/hydra/pull/856, the `type`-related constraints
were a bit too loose, allowing some variations that should have been seen as
invalid. This commit adds a test (inspired by
https://github.com/NixOS/hydra/pull/856#issuecomment-772820929) to ensure these
constraints stay unviolated.

Jobset: test `type`-related constraints

---

src/sql/hydra.sql

We no longer need to generate the hydra-postgres.sql document,
that is a relic from when sqlite was also supported.

hydra.sql: Update comment on regeneration

---

src/script/hydra-notify

This is more consistent with the other event handlers, of dealing
with IDs and not objects.

hydra-notify: move buildFinished query in to the function impl

---

src/lib/Hydra/Plugin/DeclarativeJobsets.pm
src/script/hydra-notify

Declarative jobsets were sort of tucked in to the event handler
itself. It turned out that it could have been implemented as a
plugin without much trouble.
Declarative jobsets have no tests, so this should be tested
by hand.

Declarative jobsets: move event handling to a plugin

---

src/lib/Hydra/Event.pm
src/lib/Hydra/Event/BuildFinished.pm
src/lib/Hydra/Event/BuildStarted.pm
src/lib/Hydra/Event/StepFinished.pm
src/script/hydra-notify
t/Event.t
t/Event/BuildFinished.t
t/Event/BuildStarted.t
t/Event/StepFinished.t

~_Note: This PR includes #995, #996, and #997._~
This PR seeks to improve the hydra-notify script by increasing test coverage and creating abstractions over messages and events and how those are processed. A key change here is the parsing and processing of an event type is collected in to a per-event-type class.
This PR is part of a larger effort to add support for retrying notifications.

hydra-notify: abstract event handling, make testable

---

src/lib/Makefile.am

Event/*.pm files were not included in the final Nix store result. Not sure how to test this in PRs.

lib/makefile: include Event/*.pm

---

flake.nix
src/script/hydra-notify

If anything, these little fixups are a strong argument for moving more code out of hydra-notify and in to a structure with `.t` files.
Sorry for the issues :sweat:.

#998: Batch of fixups

---

flake.nix

The test seems to be broken for a while[1]. The cause for this is that
in gitea 1.14 the `create-user` command got renamed to `user create`.
[1] https://hydra.nixos.org/build/151092299
cc @grahamc

gitea-plugin: fix test

---

src/lib/Hydra/Controller/Job.pm
src/lib/Hydra/Controller/JobsetEval.pm
src/lib/Hydra/Event/BuildFinished.pm
src/lib/Hydra/Helper/CatalystUtils.pm
src/lib/Hydra/Plugin/BitBucketStatus.pm
src/lib/Hydra/Plugin/CircleCINotification.pm
src/lib/Hydra/Plugin/CoverityScan.pm
src/lib/Hydra/Plugin/EmailNotification.pm
src/lib/Hydra/Plugin/GiteaStatus.pm
src/lib/Hydra/Plugin/GithubStatus.pm
src/lib/Hydra/Plugin/GitlabStatus.pm
src/lib/Hydra/Plugin/HipChatNotification.pm
src/lib/Hydra/Plugin/SlackNotification.pm

Implementing part of #1003: 
> Using $a or $b outside sort() at line 45, column 16.  $a and $b are special package variables for use in sort() and related functions. Declaring them as lexicals like "my $a" may break sort(). Use different variable names.  (Severity: 4)
Care should be taken to verify each commit doesn't stomp on existing variables in scope.

Avoid $a, $b

---

src/lib/Hydra/Math.pm
src/lib/Hydra/Schema/Result/TaskRetries.pm
src/lib/Hydra/Schema/ResultSet/TaskRetries.pm
src/lib/Hydra/Task.pm
src/lib/Hydra/TaskDispatcher.pm
src/script/hydra-notify
src/sql/hydra.sql
src/sql/update-dbix.pl
src/sql/upgrade-77.sql
t/Math.t
t/Schema/Result/TaskRetries.t
t/Schema/ResultSet/TaskRetries.t
t/TaskDispatcher.t

Hydra's `hydra-notify` process is currently fire-and-forget.
This is troublesome for plugins that implement important behaviors
for Hydra as the result of plugins. For example, declarative jobsets
can mysteriously fail to update if its plugin misbehaves and fails
during its execution.
This pull request adds an element of retries to `hydra-notify`.
Every event that comes from Postgres's LISTEN/NOTIFY channel is turned
in to an Event: a parsed version of the data, plus the original raw
payload. The status quo is every Plugin is then executed with this 
Event.
This pull request adds an additional step. The Event is turned in to a
Task, which is an Event with an attached Plugin name. The Task is then
executed by the TaskDispatcher. If the Task fails, the dispatcher saves
the Task in a …

Retryable notifications

---

src/lib/Hydra/Schema/ResultSet/TaskRetries.pm
src/script/hydra-notify
t/Schema/ResultSet/TaskRetries.t

Yet again, manual testing is proving to be insufficient. I'm pretty
sure I wrote this code but lost it in a rebase, or perhaps the switch
to result classes.
At any rate, this implements the actual "fetch a retry row and run it"
for the hydra-notify daemon.
Tested by hand.

ResultSet::TaskRetries: add missing method, get_retryable_task

---

flake.nix

https://hydra.nixos.org/jobset/hydra/master#tabs-errors
"passwords were replaced with salted sha1 instead of sha256, because I
don't want to have to figure out how to make slapd load this module
We could also just do {CLEARTEXT} for the purpose of this test"

fix ldap nixos test

---

hydra-module.nix

In NixOS, the user generation script was changed to set the permissions `0700`
to a home-directory that's specified in the `users.users`-submodule with
`createHome` being set to `true`[1].
However, the home-directory of `hydra` is also the base directory of other services using
other users (e.g. `hydra-queue-runner`). With permissions being `0700`, processes with
such a user cannot traverse into `/var/lib/hydra` and thus not into subdirectories.
I guess that this issue was kind of hidden because `hydra-init.service` ensures
proper permissions[2]. However, if `hydra-init.service` is not restarted on a
system-activation, the permissions of `/var/lib/hydra` will be set back to `0700`
by the activation script that runs on each activation.
This has lead to errors like this in …

hydra-module: don't use `createHome = true;` to create Hydra's base-dir

---

src/root/jobset-eval.tt

When I take a look at *all* failing builds (by clicking at `[...] more
jobs omitted`) and I try to compare the failures to another jobset, I'd
like to still view *all* failing builds in the compare-view.
This wasn't the case before since the `full=`-param was ignored by the
compare-buttons.
cc @grahamc

jobset-eval: pass `full` parameter to "Compare to..."

---

src/root/Makefile.am

Fixes
```
mv: cannot move './static/bootstrap-4.3.1-dist' to './static/bootstrap/bootstrap-4.3.1-dist': Directory not empty
```
when 'make' is called more than once.

Fix building $(srcdir)/static

---

src/lib/Hydra/Controller/Job.pm
src/root/job.tt

/metrics-tab matches a rule in one of uBlock Origin's default blocklists, so let's name it something else.
This can be seen on https://hydra.nixos.org/job/nixpkgs/trunk/metrics#tabs-charts.

Fix 'Error loading tab: 0 error' with uBlock Origin

---

src/hydra-eval-jobs/hydra-eval-jobs.cc

In a similar vein to #888 allow users to configure purity.
The main reason for this is to support legacy nix code which may call things like `builtins.currentSystem`. With large highly coupled code bases, it's often the case that there is a lot of IFD and impurity going on...

Allow for evaluator_pure_eval to be configured

---

t/Controller/Build/constituents.t

This is causing CI to fail after #1026 merged. #1026 had a green
bill of health, but #1003 increased perlcritic to level 4. #1003
was not part of #1026 so it was not checked at perlcritic level 4.

constituents test: add use warnings

---

src/sql/update-dbix.pl

Prevents authors from mistakenly corrupting the hashes. This won't delete custom code at the end of the files, but it will overwrite the "protected" section that authors should not change.

update-dbix: overwrite modifications

---

src/script/hydra-eval-jobset

Sometimes evaluations will print errors about fetches. These can be hard to diagnose if you have many inputs. These log lines should help.

hydra-eval-jobset: log fetches and evaluations

---

t/View/TT.t
t/build-products.t
t/evaluate-basic.t
t/lib/CliRunners.pm
t/lib/HydraTestContext.pm
t/lib/Setup.pm
t/queue-runner/default-machine-file.t
t/queue-runner/notifications.t

Instead of passing a bunch of arguments and hashes around everywhere, let's try a test context object.
Initially I hoped making a test context object would help reduce confusing errors from the test harness while the database shuts down. This work does help with that but doesn't fully solve the problem.
While I was at it, I noticed a very common pattern of:
```perl
my $project = $db->resultset('Projects')->create({name => "tests", displayname => "", owner => "root"});
my $jobset = createBaseJobset("default-machine-file", "default-machine-file.nix", $ctx{jobsdir});
ok(evalSucceeds($jobset),               "Evaluating jobs/default-machine-file.nix should exit with return code 0");
is(nrQueuedBuildsForJobset($jobset), 1, "Evaluating jobs/default-machine-file.nix should result in 1 build"); …
```

HydraTestContext: init a context object for helpers

---

src/lib/Hydra/Controller/Root.pm
t/Controller/Root/queue-runner-status.t

from_json was legacy / deprecated. This was the only use.

queue-runner-status: fixup from perlcritic-level-2

---

src/script/hydra-notify

Currently we only track how long individual plugins take.
With #1083 we stop executing a lot of plugins, but we
don't have a way to measure its practical impact on the
execution time of handling events.

hydra-notify: track the duration of handling an event

---

doc/manual/src/notifications.md
src/lib/Hydra/Event.pm
src/lib/Hydra/Event/BuildFinished.pm
src/lib/Hydra/Event/BuildQueued.pm
src/lib/Hydra/Event/BuildStarted.pm
src/lib/Hydra/Event/StepFinished.pm
src/lib/Hydra/Plugin.pm
src/lib/Hydra/Plugin/GitInput.pm
src/lib/Hydra/TaskDispatcher.pm
src/script/hydra-eval-jobset
src/script/hydra-notify
t/Event/BuildFinished.t
t/Event/BuildQueued.t
t/Event/BuildStarted.t
t/Event/StepFinished.t

In May 2017 plugin support for executing a buildQueued event was introduced in 582c39942097539aa595d6945a82c4e25ca16ff1. At the time, hydra-notify was executed every time an event was to be delivered.
A month later in June 2017, the buildQueued hook was commented out in 803833aba77e1082c14857aa26933fc7fe5ae190:
Disable the build-queued hook
This can take an excessive amount of time. For example, on
hydra.nixos.org, a call to hydra-notify takes 0.7s even if there are
no plugins. So for an eval with ~45K new builds, the calls to
hydra-notify add up to about 9 hours.
The proper fix would be to pass a list of build IDs, or an eval ID.
A couple of years later in August of 2019, buildQueued support was deleted altogether from hydra-notify when it was converted from an exec-per-event to a …

Faster notifications and buildQueued support

---

doc/manual/src/configuration.md
hydra-module.nix
src/lib/Hydra/Controller/Root.pm

The indentation in the hydra.conf makes it possible to include multi-line
strings without it being likely that the contents of the tracker
is mis-parsed or interrupts tho config parser.
It isn't impossible / foolproof probably, but it shouldn't be likely.

Fetch the tracker HTML from the config file, remove HYDRA_TRACKER

---

src/lib/Hydra/Controller/Build.pm
src/lib/Hydra/Plugin/RunCommand.pm
src/lib/Hydra/Schema/Result/Builds.pm
src/lib/Hydra/Schema/Result/RunCommandLogs.pm
src/root/build.tt
src/sql/hydra.sql
src/sql/update-dbix.pl
src/sql/upgrade-79.sql
t/Schema/Result/RunCommandLogs.t
t/plugins/RunCommand/basic.t
t/plugins/RunCommand/errno.t

I'm probably not going to do these since I'm not excited to add an opt-in-feature for this and support that ~forever:
Includes:
- #1073

RunCommand: store a log of execution and render it on the Build page

---

src/script/hydra-eval-jobset

This is useful for systems that use concurrent evals

hydra-eval-jobset: Print the jobset that is evaluated

---

src/script/hydra-eval-jobset

I'm honestly too lazy to create two commits for fixing these one-line
issues so here's one.
The first hunk fixes the name of the projectName input. This is relevant
now because it gets logged and the log message looks stupid when there
is an input without a name.
The second hunk fixes a warning when using declarative non-flake
jobsets. The implementation may look weird but it's just the same as the
logical implication operator of nix.

hydra-eval-jobset: Fix two minor bugs

---

src/lib/Hydra/Plugin/PathInput.pm

Periodically the api-test.t would fail, complaining that the second evaluation would not have a different input revision. It turns out this is very easy to happen, because the revision is just the timestamp down to seconds. This isn't a very reasonable revision, I think. Adding the hash to the revision makes it different if the content changes.
As far as I can tell this is a reasonable change and doesn't break any assumptions in Hydra.
I ran api-test.t a few hundred times and didn't get it to fail after this.

PathInput: make the hash part of the revision

---

src/lib/Hydra/Helper/CatalystUtils.pm
t/Hydra/Helper/CatalystUtils.t

Builds refs: showjobname: use project / jobset from relations, not the bulids table

---

t/jobs/hydra-eval-notifications.nix
t/lib/CliRunners.pm
t/lib/HydraTestContext.pm
t/lib/Setup.pm
t/scripts/hydra-eval-jobset/notifications.t

This is an addition of a simple test which compares the NOTIFY/LISTEN events received vs. expected. This is an attempt at putting some tests around the behavior of hydra-eval-jobset without changing its structure much.

hydra-eval-jobset: test emitted notifications

---

doc/manual/src/notifications.md
src/lib/Hydra/Event.pm
src/lib/Hydra/Event/CachedBuildFinished.pm
src/lib/Hydra/Event/CachedBuildQueued.pm
src/lib/Hydra/Plugin.pm
src/script/hydra-eval-jobset
src/script/hydra-notify
t/Event/CachedBuildFinished.t
t/Event/CachedBuildQueued.t
t/scripts/hydra-eval-jobset/notifications.t

These new notifications allow plugins to operate on existing builds being reused by a new evaluation. A key example of this is for sending "queued" and "finished" notifications to systems like GitHub. See: https://github.com/DeterminateSystems/hydra/pull/6
Note this does not reuse build_finished or build_queued because those might perform tasks that are very noisy assuming a low execution rate per build. Furthermore, those events operate on _all_ evaluations the build is part of, and these events operate only on the specific evaluation which is new.
This will send many thousand notifications per evaluation for Nixpkgs / NixOS on hydra.nixos.org, so before merging this I want to deploy it and see how it impacts the database and hydra-notify's performance.

hydra-eval-jobset: send cached_build_finished, cached_build_queued

---

src/lib/Hydra/Controller/API.pm
t/Hydra/Controller/API/checks.t
t/jobs/one-job.nix

The picked commit in this case was `Fixup project name, jobset name, in buildToHash`. After implementing a test for that behavior I noticed a handful of other codepaths that used project and jobset, so I fixed those too. I thought the `push*` APIs used them, but they don't.

Project jobset: api: update endpoints to stop using build.{project,jobset}

---

src/lib/Hydra/Controller/Root.pm
src/root/search.tt
t/Hydra/Controller/Root/status.t

The picked commit in this case was `search: fix references to jobset / project info`.

Project jobset: update search

---

src/lib/Hydra/Controller/Project.pm
t/Hydra/Controller/Project/delete.t

Deleting jobsets first would fail because buildmetrics has an FK
to the jobset. However, the jobset / project relationship is not
marked as CASCADE.
Deleting all the builds automatically cascades to delete
buildmetrics, so deleting the relevant builds first, then deleting
the jobset solves it.
Closes #1081 
cc @dasJ @ajs124 @cole-h

Projects: delete: delete all builds first

---

src/script/hydra-eval-jobset

The picked commit in this case was `hydra-eval-jobset: fixup old reference to project / jobset columns`.

Project jobset: update input type "build"

---

.gitignore
configure.ac
src/lib/Hydra/Controller/Project.pm
src/lib/Hydra/Plugin/DeclarativeJobsets.pm
t/Hydra/Plugin/DeclarativeJobsets/basic.t
t/jobs/declarative/generator.nix
t/jobs/declarative/generator.sh
t/jobs/declarative/project.json.in

In this case there was no failing test so I wrote one, and extracted the "get the jobset name from the jobset table" commit.

Project jobset: Update DeclarativeJobsets to not use the project or jobsets columns on Bulids

---

src/script/hydra-update-gc-roots
t/scripts/hydra-update-gc-roots/update-gc-roots.t

In this case, there were no tests for updating GC roots. I added a basic test validating the program executed. This caught several issues in the removal of these columns, which I've fixed in this PR. This PR should be independently valid.

Project jobset: update-gc-roots

---

src/hydra-queue-runner/queue-monitor.cc
src/hydra-queue-runner/state.hh

In this case, a lot of tests failed before, and they all pass now. However, as little as I know Perl, I know C++ even less. I'd love to have actual C++-level tests if possible. I'd also like it if someone who knows C++ reviewed this.

queue-runner: track jobsets by ID

---

src/lib/Hydra/Controller/Root.pm
src/lib/Hydra/Plugin/EmailNotification.pm
src/lib/Hydra/Plugin/HipChatNotification.pm
src/lib/Hydra/Plugin/InfluxDBNotification.pm
src/lib/Hydra/Plugin/SlackNotification.pm
src/lib/Hydra/Schema/Result/Builds.pm
src/lib/Hydra/Schema/Result/Jobsets.pm
src/lib/Hydra/Schema/Result/Projects.pm
src/script/hydra-eval-jobset
src/sql/hydra.sql
src/sql/upgrade-80.sql

This is a work in progress PR which is not carefully validated. The tests do pass which is nice to see. However, I've barely even started the webserver or clicked around.
The project and jobset columns were the only foreign key to a jobset and project. #969 added a jobset_id as a replacement, but didn't go all the way to dropping the now duplicate columns. This PR finishes that.
I think a good way to apply this PR is to pull out individual commits, updating individual systems and merging / deploying them one at a time, validating in production that the change didn't break anything. This way, we can easily revert changes if it is the easiest solution.
Several commits in this PR implemented the easiest possible solution to make a test pass. Those patches should be undone, and reimplemented. …

Builds: drop the jobset and project columns

---

doc/manual/src/configuration.md

When trying to get LDAP integration to work I naively copied the example YAML config file, but later saw that there was a typo, making it invalid. This adds the missing colon.

Fix invalid YAML in documentation

---

src/script/hydra-create-user
t/scripts/hydra-create-user.t

The instructions there would include the `\n` in the password hash.
Closes #1128

Fixup argon2 instructions in hydra-create-user

---

README.md
doc/dev-notes.txt
doc/manual/src/installation.md
flake.nix
src/lib/Hydra/Helper/Nix.pm
src/script/hydra-create-user
t/lib/CliRunners.pm
t/lib/Setup.pm
t/scripts/hydra-create-user.t

Original body:
> I'm not sure this is a good implementation as-is. It does work,
> but the password gets echo'd to the screen. I tried to use IO::Prompt
> but IO::Prompt really seems to want to read the password from ARGV.
but now it is noecho, so I think it should be good to go.

hydra-create-user: support prompting for password

---

src/hydra-queue-runner/build-remote.cc
t/jobs/dependencies/dependency.nix
t/jobs/dependencies/dependentOnly.nix
t/jobs/dependencies/underlyingOnly.nix
t/lib/CliRunners.pm
t/lib/HydraTestContext.pm
t/queue-runner/build-locally-with-substitutable-path.t

In a Hydra instance I saw:
possibly transient failure building ‘/nix/store/X.drv’ on ‘localhost’:
dependency '/nix/store/Y' of '/nix/store/Y.drv' does not exist,
and substitution is disabled
This is confusing because the Hydra in question does have substitution enabled.
This instance uses:
keep-outputs = true
keep-derivations = true
and an S3 binary cache which is not configured as a substituter in the nix.conf.
It appears this instance encountered a situation where store path Y was built
and present in the binary cache, and Y.drv was GC rooted on the instance,
however Y was not on the host.
When Hydra would try to build this path locally, it would look in the binary
cache to see if it was cached:
(nix)
439      bool valid = isValidPathUncached(storePath);
440
441      if (diskCache && …

build-remote: copy missing paths from the binary cache to localhost

---

src/lib/Hydra/Plugin/GithubStatus.pm

When a cached build queued / build finished event comes along, push it as a commit status to GitHub.

GithubStatus: try pushing statuses for cached buildqueued/buildfinished events

---

doc/manual/src/notifications.md
src/lib/Hydra/Event.pm
src/lib/Hydra/Event/EvalAdded.pm
src/lib/Hydra/Event/EvalCached.pm
src/lib/Hydra/Event/EvalFailed.pm
src/lib/Hydra/Event/EvalStarted.pm
src/lib/Hydra/Plugin.pm
src/script/hydra-eval-jobset
src/script/hydra-notify
t/Hydra/Event/EvalAdded.t
t/Hydra/Event/EvalCached.t
t/Hydra/Event/EvalFailed.t
t/Hydra/Event/EvalStarted.t
t/scripts/hydra-eval-jobset/notifications.t

Needs:
The old format for these events used the two-character string `\t` as a separator between the fields. I wasn't going to break these event's message format until I saw this and assumed nobody used it. I assume if nobody reported the bug nobody used it. It is obviously a bug that it isn't a tab character. If somebody did depend on such an obvious bug without reporting it, well, oops.
This PR lets plugins attach to evalStarted, evalCached, evalFinished, evalFailed, evalAdded events. This is useful for sending status events to, eg, GitHub (PR soon.)
Note this PR includes #1144 which is fixups originally part of this branch.

`eval_*` events: change the API to include IDs and use \t separators

---

src/lib/Hydra/Helper/Exec.pm
src/lib/Hydra/Helper/Nix.pm
src/lib/Hydra/Plugin/BazaarInput.pm
src/lib/Hydra/Plugin/DarcsInput.pm
src/lib/Hydra/Plugin/MercurialInput.pm
src/lib/Hydra/Plugin/SubversionInput.pm
src/script/hydra-eval-jobset
t/Hydra/Controller/Jobset/channel.t
t/Hydra/Plugin/RunCommand/basic.t
t/lib/CliRunners.pm
t/lib/Setup.pm
t/queue-runner/build-locally-with-substitutable-path.t
t/scripts/hydra-create-user.t
t/scripts/hydra-init.t
t/scripts/hydra-send-stats.t
t/scripts/hydra-update-gc-roots/update-gc-roots.t

Using Hydra::Helper::Nix in tests causes environment variables like HYDRA_DBI to be fixated too early, making us `require` it. A common reason to do this in a test is to access captureStdoutStderrWithStdin. This PR moves those functions to a new helper.

captureStdoutStderr*: move to Hydra::Helper::Exec which helps avoid some environment variable fixation problems

---

src/root/static/css/hydra.css

build-graphs: Fix readability in dark mode

---

src/script/hydra-eval-jobset
t/evaluator/evaluate-constituents-broken.t
t/jobs/constituents-broken.nix
t/lib/HydraTestContext.pm

Closes #1090.
Changes:
> 1{UNKNOWN}: Died at /nix/store/bj4ihx5hnmb51isf59j869wc1mhxqs28-hydra-0.1.20211223.76962bf/bin/.hydra-eval-jobset-wrapped line 779. at /nix/store/w6an5b9802y52k4x2d1cj3ngyx35mfsn-hydra-perl-deps/lib/perl5/site_perl/5.34.0/Catalyst/Model/DBIC/Schema.pm line 526
to:
> {UNKNOWN}: aggregate job ‘mixed_aggregate’ failed with the error: constituentA: does not exist at xxx

Broken constituents: emit useful log messages on evaluation errors on constituents

---

src/script/hydra-update-gc-roots
t/scripts/hydra-update-gc-roots/update-gc-roots.t

Re-executing this search_related on every access turned out to
create very problematic performance. If a jobset had a lot of
error output stored in the jobset, and there were many hundreds
or thousands of active jobs, this could easily cause >1Gbps of
network traffic.

hydra-update-gc-roots: allow cached refs to the build's jobset

---

src/hydra-queue-runner/build-remote.cc
src/hydra-queue-runner/queue-monitor.cc

It is more terse, and in the future it is possible `copyClosure` will
become more sophisticated.
Depends on https://github.com/NixOS/nix/pull/5949

Use `copyClosure` instead of `computeFSClosure` + `copyPaths`

---

flake.lock
flake.nix
src/hydra-queue-runner/build-remote.cc
src/hydra-queue-runner/queue-monitor.cc
t/jobs/empty-dir-builder.sh

Hydra has been having mysterious issues recently, and we believe it may be related to the jump from 2.4preXYZ to 2.6.0. We test 2.5.1 as a way to bisect.

Revert to Nix 2.5.1

---

flake.nix
hydra-module.nix

As suggested in https://github.com/NixOS/nixos-search/issues/125#issue-653965820
Makes `nix run github:nixos/nixos-search#flake-info -- flake github:nixos/hydra` succeed.
The `lastModifiedDate` fill is just so that we can run that command as `flake-info flake ./hydra` too.

Prepare for nixos-search integration

---

doc/architecture.md

meeting notes from @edolstra giving a one-hour tour of the code
@tomberek @Ericson2314
suggestion: move contributor guidelines to the new `CONTRIBUTING.md` once it's merged.

add contributor's guide with architecture notes

---

src/hydra-eval-jobs/hydra-eval-jobs.cc
t/evaluator/evaluate-oom-job.t
t/jobs/oom.nix

When evaluating jobs using `hydra-eval-jobs` it's possible for the evaluation to fail in various unexpected ways, such as consuming more than the available memory, which in turn can trigger `OOMKiller` on child worker processes of `hydra-eval-jobs`. When `hydra-eval-jobs` attempts to interact with a dead child process by reading or writing to the file descriptors `to`/`stdin` and `from`/`stdout` pipes attached to the child process, [`readLine`](https://github.com/NixOS/nix/blob/ee57f91413c9d01f1027eccbe01f7706c94919ac/src/libutil/util.cc#L387-L405) reaches and throws [`EndOfFile`](https://github.com/NixOS/nix/blob/ee57f91413c9d01f1027eccbe01f7706c94919ac/src/libutil/util.cc#L399) and [the thread which is responsible for that process cleans up and exits, while also notifying any other …

hydra-eval-jobs: Report forked worker process status information on exception

---

src/lib/Hydra/Plugin/GithubPulls.pm

Thank you @dasJ for this fix
(If someone finds this while searching for a working setup with dynamic jobs you can look here: https://github.com/anmonteiro/nix-overlays/pull/299)

GithubPulls: Don't fail on missing `Link`

---

src/lib/Hydra/Plugin/GitInput.pm

I started to wonder quite recently why Hydra doesn't send email
notifications anymore to me. I saw the following issue in the log of
`hydra-notify.service`:
May 22 11:57:29 hydra 9bik0bxyxbrklhx6lqwifd6af8kj84va-hydra-notify[1887289]: fatal: unsafe repository ('/var/lib/hydra/scm/git/3e70c16c266ef70dc4198705a688acccf71e932878f178277c9ac47d133cc663' is owned by someone else)
May 22 11:57:29 hydra 9bik0bxyxbrklhx6lqwifd6af8kj84va-hydra-notify[1887289]: To add an exception for this directory, call:
May 22 11:57:29 hydra 9bik0bxyxbrklhx6lqwifd6af8kj84va-hydra-notify[1887289]:         git config --global --add safe.directory /var/lib/hydra/scm/git/3e70c16c266ef70dc4198705a688acccf71e932878f178277c9ac47d133cc663
May 22 11:57:29 hydra 9bik0bxyxbrklhx6lqwifd6af8kj84va-hydra-notify[1886654]: error …

Fix email notifications for jobsets w/git-inputs

---

flake.lock
flake.nix
src/hydra-eval-jobs/Makefile.am
src/hydra-eval-jobs/hydra-eval-jobs.cc
src/hydra-queue-runner/queue-monitor.cc

NOTE: I'm well-aware that we have to be careful with this to avoid new
regressions on hydra.nixos.org, so this should only be merged after
extensive testing from more people.
Motivation: I updated Nix in my deployment to 2.9.1 and decided to also
update Hydra in one go (and compile it against the newer Nix). Given
that this also updates the C++ code in `hydra-{queue-runner,eval-jobs}`
this patch might become useful in the future though.

flake: Update Nix to 2.9.1

---

src/lib/Hydra/Helper/AddBuilds.pm
t/Helper/AddBuilds/dynamic-disabled.t
t/Helper/AddBuilds/dynamic-enabled.t

$project->{enable_dynamic_run_command} is undefined
Currently fails with `ERROR: failed to process declarative jobset […]:[…], Dynamic RunCommand is not enabled by the server or the parent project. at /nix/store/[…]/libexec/hydra/lib/Hydra/Helper/AddBuilds.pm line 72.`.

AddBuilds: fix declarative jobsets with dynamic runcommand enabled

---

src/lib/Hydra/Controller/Build.pm
src/lib/Hydra/Helper/Nix.pm

the former was deprecated in favor of the latter

replace nix cat-store with nix store cat

---

flake.nix
src/lib/Hydra/Controller/Build.pm

MIME::Types isn't flexible enough to detect the correct MIME type since it only goes off of the file name, which breaks for file names without extensions. This changes MIME detection to use libmagic which also takes the file contents into account. I took out the path that calls serve_static_file since that function also uses MIME::Types internally.
Closes #1184.

Use libmagic for better output MIME detection

---

doc/manual/src/configuration.md

To group is called `cancel-build`, not `cancel-builds` (note the
trailing `s`).
cc @grahamc @dasJ

doc/configuration: fix ldap role mapping example

---

hydra-module.nix

nix.trustedUsers is deprecated as of 22.05, and since the nix.extraOptions config is just doing something similar, I moved that to the new nix.settings as well

Update hydra-module.nix to use newer nixos options

---

src/root/build-deps.tt
src/root/build.tt
src/root/common.tt
src/root/deps.tt
src/root/static/css/hydra.css
src/root/static/css/tree.css
src/root/static/js/common.js

Turns out the code has been there all along, it just didn't play nice with lazy tab loading.
Disclaimer: my JS is bad and my Perl is even worse, but this _should_ work.

Run the JS code to make build trees collapsible at the right time

---

src/lib/Hydra/Controller/Job.pm
t/Hydra/Controller/Job/builds.t

Since we already expose Prometheus metrics for jobs, I figured that these two values are also reasonable to expose :) 
cc @grahamc @dasJ @lheckemann

Job: expose `closuresize` and `size` (output size in the UI) as prometheus metrics

---

doc/manual/src/projects.md

Bring the manual in line with the [configuration documentation](https://github.com/NixOS/hydra/blob/master/doc/manual/src/configuration.md#including-files)

Fix insecure advice in the manual

---

src/lib/Hydra/Controller/API.pm

The newest version of git refuses to work on repositories not owned by
the current user. This leads to issues with the `/api/scmdiff` endpoint:
```
May 27 11:16:05 myhydra hydra-server[923698]: fatal: unsafe repository ('/var/lib/hydra/scm/git/57ea036ec7ecd85c8dd085e02ecc6f12dd5c079a6203d16aea49f586cadfb2be' is owned by someone else)
May 27 11:16:05 myhydra hydra-server[923698]: To add an exception for this directory, call:
May 27 11:16:05 myhydra hydra-server[923698]:         git config --global --add safe.directory /var/lib/hydra/scm/git/57ea036ec7ecd85c8dd085e02ecc6f12dd5c079a6203d16aea49f586cadfb2be
May 27 11:16:05 myhydra hydra-server[923701]: warning: Not a git repository. Use --no-index to compare two paths outside a working tree
May 27 11:16:05 myhydra hydra-server[923701]: usage: …
```

scmdiff: Hardcode `--git-dir`

---

src/lib/Hydra/Controller/User.pm
t/Hydra/Controller/User/dashboard.t
t/jobs/basic.nix

Nowadays `Builds` doesn't reference `Project` directly anymore. This means that simply resolving both `jobset` and `project` with a single JOIN from `Builds` doesn't work anymore. Instead we need to resolve the relation to `jobset` first and then the relation to `project`.
For similar fixes see e.g. c7c47596009687d1652522c556333cefce28ec51.
cc @dasJ @grahamc

Fix "My Jobs" tab in user dashboard

---

src/hydra-evaluator/hydra-evaluator.cc

There's currently no automatic recovery for disconnected databases in the evaluator. This means if the database is ever temporarily unavailable, hydra-evaluator will sit and spin with no work accomplished.
If this condition is caught, the daemon will exit and systemd will be responsible for resuming the service.

exit with error if database connectivity lost

---

.github/workflows/test.yml
src/sql/upgrade-83.sql

Also it's larger than the actual table it's indexing lol.
-[ RECORD 30 ]----------+-----------------------------------------
table_name              | buildoutputs
index_name              | indexbuildoutputsonpath
index_scans_count       | 0
index_size              | 31 GB
table_reads_index_count | 2128699937
table_reads_seq_count   | 0
table_reads_count       | 2128699937
table_writes_count      | 22442976
table_size              | 28 GB

Drop unused IndexBuildOutputsOnPath index

---

hydra-module.nix

This prevents eval errors when a machine is just started and the network isn't yet online. I'm running hydra on a laptop and the network takes a bit of time to come online (WLAN), so it's nice if the evaluator starts only when the network actually goes online.
Otherwise an error like this can happen on the first eval(s):
```
error fetching latest change from git repo at `https://github.com/nixos/nixpkgs.git':
fatal: unable to access 'https://github.com/nixos/nixpkgs.git/': Could not resolve host: github.com
```
See also https://github.com/NixOS/nixpkgs/pull/216451

systemd: hydra-queue-runner: wait for network-online

---

src/hydra-queue-runner/hydra-queue-runner.cc

Apparently, jobsets / machineTypes were never correctly copied to `statusJson` without this.
cc @lheckemann @dasJ @ajs124

hydra-queue-runner: fix stats

---

hydra-api.yaml

You  need to pass it an eval-id, not a build-id pretty sure

Fix docs for  /eval/{id}  endpoint

---

hydra-api.yaml

The endpoint is implemented here:
https://github.com/NixOS/hydra/blob/00d30874da759eb0f44f446415b2469920ff41b5/src/lib/Hydra/Controller/JobsetEval.pm#L188-L196

Document all_builds (/eval/{eval-id}/builds) endpoint

---

src/root/common.tt

Nixpkgs has so many commits that length 6 is often ambiguous, making the use of the shown values with git difficult.

`renderInputDiff`: Increase git hash length 6 -> 8

---

src/lib/Hydra/Controller/Build.pm

To correctly render HTML reports we make sure to return the following MIME types instead of "text/plain"
- *.css: "text/css"
- *.js: "application/javascript"
Fixes: #1267

Fix MIME types when serving .js and .css to fix rendering of HTML reports

---

flake.lock
flake.nix
src/hydra-eval-jobs/hydra-eval-jobs.cc
src/hydra-evaluator/hydra-evaluator.cc
src/hydra-queue-runner/build-remote.cc
src/hydra-queue-runner/build-result.cc
src/hydra-queue-runner/hydra-queue-runner.cc
src/hydra-queue-runner/nar-extractor.cc
src/hydra-queue-runner/nar-extractor.hh
src/libhydra/db.hh
src/libhydra/hydra-config.hh

Depends on https://github.com/NixOS/hydra/pull/1308, which we should definitely merge first (and not skip a Nix release).

Upgrade to Nix 2.19

---

README.md
bootstrap
flake.nix

- `nativeBuildInputs` vs `buildInputs`
- narrow down `with`s for clarity
- use `autoreconfHook` not `bootstrap` script
These sorts of changes have also been done in the Nix repo.

Cleanup deps

---

src/hydra-queue-runner/dispatcher.cc

The previous implementation was O(N²lg(N)) due to sorting the full runnables priority list once per runnable being scheduled. While not confirmed, this is suspected to cause performance issues and bottlenecking with the queue runner when the runnable list gets large enough.
This commit changes the dispatcher to instead only sort runnables per priority once per dispatch cycle. This has the drawback of being less reactive to runnable priority changes: the previous code would react immediately, while this might end up using "old" priorities until the next dispatch cycle. However, dispatch cycles are not supposed to take very long (seconds, not minutes/hours), so this is not expected to have much or any practical impact.
Ideally runnables would be maintained in a sorted data structure instead …

queue-runner: only re-sort runnables by prio once per dispatch cycle

---

src/hydra-queue-runner/build-remote.cc

This matches Nix (in the same serialization logic in `src/libstore/legacy-ssh-store.cc`) and adds clarity.

`copyClosureTo`: Use `SubstituteFlag` instead of `bool`

---

t/lib/HydraTestContext.pm

Since `nix-next` is like the `staging` branch, could we reuse the automation to do this automatically?

Mere `master` into `nix-next`

---

flake.lock
src/hydra-queue-runner/build-remote.cc
src/hydra-queue-runner/builder.cc
src/hydra-queue-runner/state.hh

Use `ServeProto::BuildOption`

---

src/hydra-queue-runner/build-remote.cc

The interesting part is the preparatory commit:
> Do not attempt to speak a newer version of the protocol
>
> Both sides need to agree on a version (with `std::min`) for anything to work. Somehow... we've never done this.
>
> With this comment, the next commit succeeds. Without this commit, the next commit fails. This is because the next commit exposes serializers which do different things for proto version 2.7, and we're currently requesting 2.6.
>
> Opened https://github.com/NixOS/nix/issues/9584 to track this issue

Use `ServeProto::Serialise<ServeProto::BuildOptions>`

---

src/hydra-queue-runner/queue-monitor.cc

Instead of doing this partial operation a number of times, assert (with a comment, get a reference to the thing inside, and use that just once. (This refactor was done twice, "just once" for each time.)

Clean up `std::optional` dereferencing in the queue runner

---

src/hydra-queue-runner/build-remote.cc
src/hydra-queue-runner/state.hh

After a few preparatory moves, this does `cmdQueryValidPaths`
See each commit for details and easier reviewing.
Progress towards https://github.com/NixOS/hydra/issues/1164
This targets `nix-next` not `master`, so it is fine that this depends on an unreleased version of Nix. Only the Nix PR needs to be merged first.
Depends on https://github.com/NixOS/nix/pull/6134
~~Depends on #1324~~

Begin factoring out the protocol code

---

src/hydra-queue-runner/queue-monitor.cc

A slight dedup, and also ensures that floating CA derivations require a `ca-derivations` experimental feature. This fixes the scheduling issue that @SuperSandro2000 found.

Use `nix::ParsedDerivation::getRequiredSystemFeatures()`

---

src/hydra-queue-runner/hydra-queue-runner.cc

We have to oddly make a `StoreConfig` subclass to get it, but https://github.com/NixOS/nix/pull/9848 will fix that.
The purpose of this is to ensure that, absent an explicit config, `localhost` includes `ca-derivations` and `recursive-nix` if those experimental features are enabled.
Very much the complement of #1342, the previous PR.

Use `StoreConfig::getDefaultSystemFeatures` for default machine config

---

src/root/topbar.tt

Self-explanatory, if you've used Hydra without being logged in the last few months.
Documentation: https://developers.google.com/identity/gsi/web/reference/html-reference#data-auto_prompt

web: disable Sign in with Google popup

---

src/hydra-eval-jobs/hydra-eval-jobs.cc
src/hydra-queue-runner/hydra-queue-runner.cc
src/hydra-queue-runner/queue-monitor.cc
src/lib/Hydra/Controller/Build.pm
src/script/hydra-eval-jobset
t/lib/HydraTestContext.pm

Again, with care not to change the schema in any way.

More CA derivations prep

---

doc/manual/src/hacking.md
package.nix

cc @Ericson2314 
In 5db374c the `bootstrap` script was
removed, however it's still referenced in the contribution guidelines.
Change that to `autoreconfPhase` as intended by the commit.
In 1bd195a strictDeps was set for the
Hydra package. As a result, `checkInputs` aren't available anymore in
the local dev-shell which is the sole purpose of foreman, to start
services and a database for development.

Small fixes for the development environment

---

doc/manual/src/projects.md
src/lib/Hydra/Controller/Root.pm
src/lib/Hydra/Schema/Result/BuildOutputs.pm
src/lib/Hydra/Schema/Result/BuildStepOutputs.pm
src/sql/hydra.sql
src/sql/upgrade-84.sql
t/content-addressed/basic.t
t/content-addressed/without-experimental-feature.t
t/jobs/config.nix.in
t/jobs/content-addressed.nix
t/jobs/dir-with-file-builder.sh
t/queue-runner/notifications.t

This verison has a worse UI, but also chnages the schema less: One non-null constraint is removed, but no new columns are added.

Allow building content-addressed derivations with hydra, minimally

---

flake.lock
src/hydra-eval-jobs/hydra-eval-jobs.cc
src/hydra-evaluator/hydra-evaluator.cc
src/hydra-queue-runner/queue-monitor.cc
src/lib/Hydra/Base/Controller/NixChannel.pm
src/lib/Hydra/Controller/Build.pm
src/lib/Hydra/Controller/Root.pm
src/lib/Hydra/Helper/Nix.pm
src/lib/Hydra/Plugin/BazaarInput.pm
src/lib/Hydra/Plugin/DarcsInput.pm
src/lib/Hydra/Plugin/GitInput.pm
src/lib/Hydra/Plugin/MercurialInput.pm
src/lib/Hydra/Plugin/PathInput.pm
src/lib/Hydra/Plugin/SubversionInput.pm
src/lib/Hydra/View/NARInfo.pm
src/script/hydra-eval-jobset
src/script/hydra-update-gc-roots
t/s3-backup-test.pl

For https://github.com/NixOS/nix/pull/9863
cc @Ericson2314 @dasJ

Update perl bindings for nix#9863

---

flake.nix
src/lib/Hydra/Plugin/GiteaStatus.pm

This is an integration test that confirms that jobset definitions from git repositories are correctly built and status updates pushed to the gitea instance. The following things needed to be fixed:
* We're still on 23.05 where gitea is marked as insecure. Not going to update nixpkgs right now, but going for the quick fix.
* Since gitea 1.19 tokens have scopes that describe what's possible. Not specifying the scope in the DB appears to imply that no permissions are granted.
* Apparently we have three status updates now (for three status hooks, queued/started/finished). No idea why that was broken before, but the behavior still looks correct.
cc @Ericson2314 is there anything keeping us from updating nixpkgs btw?

flake: fix gitea integration test

---

src/hydra-queue-runner/hydra-queue-runner.cc
src/hydra-queue-runner/queue-monitor.cc
src/hydra-queue-runner/state.hh

Closes #1336
When restarting postgresql, the connections are still reused in `hydra-queue-runner` causing errors like this
main thread: Lost connection to the database server.
queue monitor: Lost connection to the database server.
and no more builds being processed.
`hydra-evaluator` doesn't have that issue since it crashes right away. We could let it retry indefinitely as well (see below), but I don't want to change too much.
If the DB is still unreachable 10s later, the process will stop with a non-zero exit code because of a missing DB connection. This however isn't such a big deal because it will be immediately restarted afterwards. With the current configuration, Hydra will never give up, but restart (and retry) infinitely. To me that seems reasonable, i.e. to retry DB connections on …

hydra-queue-runner: drop broken connections from pool

---

src/root/auth.tt

It's a pet peeve from me when logging into my personal Hydra that I always have to press the button rather than hitting Return after entering my password.
Reason for that is that the form doesn't have a "submit" button, so far it was always listened to the "click" event. Submit does that and you can hit Return alternatively.
cc @dasj @Ericson2314

Use `submit` event in login form

---

src/lib/Hydra/Helper/Nix.pm
t/content-addressed/basic.t
t/jobs/content-addressed.nix

See commit messages for some more background and analysis.
I set up my hydra server with the recent content-addressed derivations support, and ran into some /build/\<id\> pages that didn't want to render correctly (not only ca-derivations, other pages also suffered from this). I think I found the issue and have worked around/resolved it.
Also adds a test that verifies that the page doesn't load properly before the patch is applied. In the next commit this bug is resolved.
```
[  FAIL  ]  job  1  + The 'build' page for build 'caDependingOnFailingCA' should load properly
```

ca-derivations: fix rendering issue

---

flake.nix

It's in Nixpkgs for a good while now.

Remove `PrometheusTiny` from overlay

---

flake.nix
nixos-modules/default.nix
nixos-modules/hydra.nix
nixos-tests.nix

Nixpkgs only contains a `hydra_unstable`, not `hydra`, package, so adjust the default accordingly, and then override it to our package in the separate module which does that.

Try again to ensure hydra module is usable

---

src/lib/Hydra/Controller/Root.pm

This fixes:
> Caught exception in Hydra::Controller::Root->realisations "Undefined subroutine &Hydra::Controller::Root::queryRawRealisation called at /nix/store/v842xb35ph8ka1yi1xanjhk4xh1pn5nm-hydra-2024-04-22/libexec/hydra/lib/Hydra/Controller/Root.pm line 371."
Tested on my instance and the 500s are fixed

Fix doi resolution after #1375

---

src/hydra-queue-runner/build-remote.cc
src/hydra-queue-runner/builder.cc
src/hydra-queue-runner/dispatcher.cc
src/hydra-queue-runner/hydra-queue-runner.cc
src/hydra-queue-runner/state.hh

With https://github.com/NixOS/nix/pull/9839, the `storeUri` field is much better structured, so we can use it while still opening the SSH connection ourselves.

Utilize `nix::Machine` more fully

---

doc/manual/src/webhooks.md
src/lib/Hydra/Controller/API.pm
src/lib/Hydra/Controller/Root.pm

The gitea webhook payload is slightly different and not compatible with the github endpoint. This PR adds a new api endpoint `/api/push-gitea` which understands the gitea webhook to trigger jobsets evaluation.

Add gitea push hook

---

doc/manual/src/hacking.md

I found that this was lacking in the documentation. This avoid having to look at foreman script.

Document the default Hydra user and port in hacking.md

---

t/evaluator/evaluate-oom-job.t
t/lib/HydraTestContext.pm
t/lib/LDAPContext.pm
t/queue-runner/build-locally-with-substitutable-path.t
t/scripts/hydra-create-user.t
t/scripts/hydra-init.t
t/test.pl

I did some testing (see how in the commit messages) to hash out any unstable tests. On pull requests and possibly also on hydra we keep running into troubles with running the tests, since they keep giving seemingly random errors (timeouts, I figured out now).
This patchset increases timeouts for some commands that kept timing out under higher load, likely resolving almost all issues we have with instability on ofborg and with local builds.
We've already disabled a test (https://github.com/NixOS/nixpkgs/pull/173887) and increased the timeout in nixpkgs itself (https://github.com/NixOS/nixpkgs/blob/24e36589b79da526f339245641ade6261dcafaf8/pkgs/development/tools/misc/hydra/unstable.nix#L210-L212). Let's now resolve this upstream for good.
Also found out that t/evaluator/evaluate-oom-job.t …

Looser timeouts, disable broken test, less verbose output

---

src/root/common.tt

See investigation on lengths required to be conflict-free in practice:
https://github.com/NixOS/hydra/pull/1258#issuecomment-1321891677
---
Reason: Got annoyed / slowed down today again that the commit `c716603a` shown in https://hydra.nixos.org/build/266559156 shows 404 on Github: https://github.com/NixOS/nixpkgs/commit/c716603a
This immediately made me suspect that somebody rewrote history (security issue), when in fact the commit is just too short.
We should not waste time with such things, so bump the length.

renderInputDiff: Increase git hash length 8 -> 12

---

doc/manual/src/plugins/README.md
nixos-modules/hydra.nix
src/lib/Hydra/Helper/Nix.pm
src/lib/Hydra/Plugin/CompressLog.pm
src/lib/Hydra/View/NixLog.pm

Basically #1219 rebased on master
- https://github.com/NixOS/nixpkgs/pull/333212

CompressLog: Add zstd compression

---

src/hydra-queue-runner/hydra-queue-runner.cc

instead of converting to double, we can convert to float right away.

hydra-queue-runner: fix compilation warning

---

flake.lock
flake.nix
package.nix
src/hydra-eval-jobs/Makefile.am
src/hydra-eval-jobs/hydra-eval-jobs.cc
src/hydra-queue-runner/dispatcher.cc
src/hydra-queue-runner/nar-extractor.cc

Probably now needs cherry-picking from https://github.com/NixOS/hydra/pull/1388

Nix 2.24 upgrade

---

nixos-modules/hydra.nix

There is an overlay for the `hydra` name, but `hydra_unstable` was used, which can refer to the nixpkgs package and lead to and outdated hydra version and requires configuring the correct package attribute downstream.

Make the in-tree package the default package

---

src/lib/Hydra/Plugin/S3Backup.pm

See https://github.com/NixOS/hydra/pull/1414#issuecomment-2412350929
The variable is defined in src/lib/Hydra/Helper/Nix.pm
Error message without this patch:
```
hydra-evaluator[PID]: Couldn't require Hydra::Plugin::S3Backup : Global symbol "$MACHINE_LOCAL_STORE" requires explicit package name (did you forget to declare "my $MACHINE_LOCAL_STORE"?) at /nix/store/xxx-hydra-0-unstable-2024-09-24/libexec/hydra/lib/Hydra/Plugin/S3Backup.pm line 95.
hydra-evaluator[PID]: Compilation failed in require at /nix/store/xxx-hydra-perl-deps/lib/perl5/site_perl/5.38.2/Module/Runtime.pm line 314.
hydra-evaluator[PID]:  at /nix/store/xxx-hydra-perl-deps/lib/perl5/site_perl/5.38.2/Module/Pluggable.pm line 32.
```
Hydra keeps running fine-ish but I think this breaks some things for other people :). Also …

S3Backup: fix compilation issue for undef MACHINE_LOCAL_STORE var

---

src/script/nix-prefetch-git

In my system logs I see this every time a new eval starts:
```
hydra-evaluator[PID]: hint: Using 'master' as the name for the initial branch. This default branch name
hydra-evaluator[PID]: hint: is subject to change. To configure the initial branch name to use in all
hydra-evaluator[PID]: hint: of your new repositories, which will suppress this warning, call:
hydra-evaluator[PID]: hint:
hydra-evaluator[PID]: hint:         git config --global init.defaultBranch <name>
hydra-evaluator[PID]: hint:
hydra-evaluator[PID]: hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hydra-evaluator[PID]: hint: 'development'. The just-created branch can be renamed via this command:
hydra-evaluator[PID]: hint:
hydra-evaluator[PID]: hint:         git branch -m <name>
```
This ensures …

nix-prefetch-git: set branch name to suppress hint from git

---

flake.lock
flake.nix
nixos-modules/default.nix
nixos-modules/hydra.nix
nixos-tests.nix

When people reach out to the git repository they probably want to use hydra from the same source.
This also removes the need for an overlay with simpler and more performant direct use of the nixpkgs passed in. Before it was re-importing nixpkgs.

make nixos module hydra from this repository by default

---

src/root/reproduce.tt

On macOS, `$TMPDIR` comes with a trailing slash:
```
bash-3.2$ echo $TMPDIR
/var/folders/_q/t4wwsxvs33j409tc1tp3t5mc0000gn/T/
```
This causes `tmpDir` to be `/var/folders/_q/t4wwsxvs33j409tc1tp3t5mc0000gn/T//build-277917310` and breaks the reproduction script.
```
❯ curl https://hydra.nixos.org/build/277917310/reproduce | bash
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4293  100  4293    0     0   4420      0 --:--:-- --:--:-- --:--:--  4416
storing inputs and results in /var/folders/_q/t4wwsxvs33j409tc1tp3t5mc0000gn/T//build-277917310...
running nix-build...
using the following invocation:
+ nix-build --arg nixpkgs '{ outPath = …
```

reproduce.tt: Use realpath for tmpDir to fix macOS compatibility

---

nixos-modules/hydra.nix

Just ordering yourself after network-online.target will not guarantee that it will be loaded. You'll have to either want or require it. Hence the following trace on recent nixpkgs versions:
```
evaluation warning: hydra-queue-runner.service is ordered after 'network-online.target' but doesn't depend on it

Make hydra-queue-runner want network-online.target

---

t/evaluator/evaluate-constituents-gc.t
t/jobs/constituents.nix
t/lib/HydraTestContext.pm

- Test how shorter names are preferred when multiple jobs resolve to the same derivation.
- Test the exact aggregate map we get, by looking in the DB.

Improve tests around constituents

---

flake.lock
flake.nix

The `flake = false;` for `nix-eval-jobs` didn't fully take before.

Clean up flake lockfile stuff

---

flake.lock

Flake lock file updates:
• Updated input 'nix':
'github:NixOS/nix/970942f45836172fda410a638853382952189eb9?narHash=sha256-jGFuyYKJjJZsBRoi7ZcaVKt1OYxusz/ld1HA7VD2w/0%3D' (2025-02-12)
→ 'github:NixOS/nix/674a87462cb93f605d4fbeef607d3453e7e5a7d8?narHash=sha256-TBoHqnIdVWhsBcL05vO2B1hSl9m//5Mz2NU%2BPMk3h3Y%3D' (2025-02-16)

Bump to newer 2.26.* Nix version

---

src/hydra-queue-runner/build-remote.cc
src/hydra-queue-runner/state.hh

In https://github.com/NixOS/nix/pull/10748 it is extended with everything we need.
---------
We are no longer explicit about reusing the same connection. However:
1. Nix's `pool` mechanism will not close valid connections; it always keeps them around in case they are of use later
2. Max connections defaults to 1, so we won't open up multiple connections.
Between these two things, we are, in fact, guaranteed to reuse the same connection from one command/query to the next.

Use `LegacySSHStore`

---

src/hydra-queue-runner/build-remote.cc
src/hydra-queue-runner/state.hh

There were some hangs caused by this. Need to fix them, ideally reproducing the issue in a test, before trying this again.
This reverts commit 4a4a0f901c70676ee47f830d2ff6a72789ba1baf.

Revert "Use `LegacySSHStore`"

---

nixos-modules/hydra.nix

On hydra.nixos.org the following happened and this is the most plausible fix I could come up with.
```
Mar 02 01:45:00 mimas systemd[1]: Started hydra-compress-logs.service.
Mar 02 01:46:20 mimas hydra-compress-logs-start[2162537]: find: ‘/var/lib/hydra/build-logs/fv/qzi69s810vppw3ld5l04q9w7grlady-system-path.drv’: No such file or directory
Mar 02 01:46:33 mimas systemd[1]: hydra-compress-logs.service: Main process exited, code=exited, status=1/FAILURE
Mar 02 01:46:33 mimas systemd[1]: hydra-compress-logs.service: Failed with result 'exit-code'.
```

Fix race condition in hydra-compress-logs

---

flake.lock
nixos-modules/default.nix
t/evaluator/evaluate-constituents-broken.t
t/evaluator/evaluate-constituents-globbing.t
t/jobs/config.nix
t/jobs/constituents-cycle-glob.nix
t/jobs/constituents-cycle.nix
t/jobs/constituents-glob-all.nix
t/jobs/constituents-glob.nix
t/jobs/constituents-no-matches.nix
t/jobs/declarative/project.json
t/queue-runner/constituents.t

Rebased the last commit from https://github.com/NixOS/hydra/pull/1433 and updated n-e-j to 2.26 release.
Closes #1425
Closes #1433

nix-eval-jobs + constituent globs

---

src/lib/Hydra/View/TT.pm
src/root/job-metrics-tab.tt

My main motivation here is to get metrics with brackets to work in order
to support "pytest" test names:
- `test_foo.py::test_bar[1]`
- `test_foo.py::test_bar[2]`
I couldn't find an "HTML escape"-style function that would generate
valid html `id` attribute names from arbitrary strings, so I went with a
hash digest instead.
(See also the previous fix for [metrics with dots](https://github.com/NixOS/hydra/commit/dc2010eafcc395308016cb5525db525585997e40#diff-b63339813e72c4a1f3700bd16f677fccc99e798d7bea3f1d43a3c6175d0747b3))

Fix rendering of metrics with special characters

---

src/script/hydra-eval-jobset

hydra-eval-jobset: do not wait on n-e-j inside transaction

---

src/hydra-queue-runner/build-remote.cc
src/hydra-queue-runner/builder.cc
src/hydra-queue-runner/dispatcher.cc
src/hydra-queue-runner/state.hh

This allows for better builder usage when the queue runner is busy. To avoid running into uncontrollable imbalances between builder/queue runner, we only release the machine reservation after the local throttler has found a slot to start copying the outputs for that build.
As opposed to asserting uniqueness to understand resource utilization, we just switch to using `std::unique_ptr`.

queue-runner: release machine reservation while copying outputs

---

package.nix
src/lib/Hydra/Controller/Jobset.pm
src/lib/Hydra/Controller/JobsetEval.pm
src/lib/Hydra/Helper/Nix.pm
src/lib/Hydra/Schema/Result/EvaluationErrors.pm
src/lib/Hydra/Schema/Result/Jobsets.pm
src/lib/Hydra/Schema/ResultSet/EvaluationErrors.pm
src/lib/Hydra/Schema/ResultSet/Jobsets.pm
src/root/common.tt
src/root/jobset-eval.tt
src/root/jobset.tt
t/evaluator/evaluate-constituents-globbing.t
t/lib/CliRunners.pm
t/queue-runner/direct-indirect-constituents.t

This is implement in an extremely hacky way due to poor DBIx feature
support. Ideally, what we'd need is a way to tell DBIx to ignore the
errormsg column unless explicitly requested, and to automatically add a
computed 'errormsg IS NULL' column in others. Since it does not support
that, this commit instead hacks some support via method overrides while
taking care to not break anything obvious.
From the hydra.nixos.org branch

web: replace 'errormsg' with 'errormsg IS NULL' in most cases

---

src/root/eval-error.tt

Closes https://github.com/NixOS/hydra/issues/1453
Closes https://github.com/NixOS/hydra/pull/1363 (was merged in https://github.com/NixOS/hydra/pull/1462)

Fix displaying eval errors in jobset eval view

---

flake.lock
flake.nix

This is what we do for `nix-eval-jobs` already. It allows for more fine-grained control over dependencies.

Use Nix without the flake

---

package.nix

We need this in nixos infra to keep both in sync.

Expose nix package in hydra package

---

src/hydra-queue-runner/dispatcher.cc

(cherry picked from commit https://git.lix.systems/lix-project/hydra/commit/b8d03adaf45105452bf1040deeaaccc8b8b22efb)
@mweinelt Was this commit ever tried on h.n.o?

queue runner: attempt at slightly smarter scheduling criteria

---

nixos-modules/hydra.nix

These have been deprecated, e.g. gc-keep-outputs is now just keep-outputs.
https://nix.dev/manual/nix/2.28/command-ref/conf-file.html#conf-keep-derivations
https://nix.dev/manual/nix/2.28/command-ref/conf-file.html#conf-keep-outputs

Migrate from "gc-" prefixed nix options

---

doc/manual/src/configuration.md

- hydra does not remove the base URI from the request before processing it, so this must be done in the reverse proxy. in nginx this is done by giving proxy_pass a URI rather than a protocol/host/port; see:
https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
- proxy_redirect is not correct/required: hydra uses proxy headers to correctly form redirects in most cases, and where it doesn't it produces local redirects which aren't matched by this directive anyway
I've tried this exact setup on both http and https, and it works fine (apart from the redirects). It might also be worth showing how to configure this in nixos, as the defaults work and that's probably more relevant to most users?
There is an existing PR for this, #1310 , which i didn't see before making this. This …

doc/manual: correct nginx reverse proxy example

---

doc/manual/src/installation.md
src/root/build.tt

Updates the documentation and `reproduce` modal to point to the correct download page for Nix.

fix: Update Nix download url

---

foreman/start-hydra.sh
foreman/start-notify.sh
src/lib/Hydra/Controller/Root.pm
src/lib/Hydra/Helper/Nix.pm
t/Hydra/Helper/Nix.t

This is guarded behind a setting and will overwrite everything that was learned from the machines file. Also drops `sshKeys` since that wasn't used anyway.

Show queue runner v2 status

---

src/root/jobset-eval.tt

This message serves no purpose and looks like something went wrong. There is nothing wrong, there is just no previous evaluation.

Remove useless previous eval message

---

.github/workflows/test.yml
doc/manual/src/hacking.md
src/hydra-evaluator/hydra-evaluator.cc
src/hydra-queue-runner/builder.cc
src/hydra-queue-runner/hydra-queue-runner.cc
src/hydra-queue-runner/queue-monitor.cc
src/libhydra/db.hh
src/script/hydra-eval-jobset

Getting parts of #1502 that should be fine, prior to the upgrade.

Libpqxx and ci

---

src/root/jobset-eval.tt

The list of jobsets is very high on hydra.nixos.org and the compare to dropdown listing goes over multiple full pages in the busy projects.
If we ignore jobsets that we disable this interface becomes more usable again.
This is untested.

jobset-eval: reduce compare options to active jobsets

---

src/script/hydra-eval-jobset

`ne` evaluates before `//` in Perl; which caused the setting
```
allow_import_from_derivation = true
```
to actually evaluate into not allowing import-from-derivation; while `0` became a value that did allow IFD.
This PR adds parentheses to fix the evaluation order, so `true` allows IFD while `0` does not anymore.

Correctly apply the setting `allow_import_from_derivation = true`

---

.perlcriticrc
src/lib/Hydra/Controller/API.pm
src/lib/Hydra/Controller/Build.pm
src/lib/Hydra/Controller/Root.pm
src/lib/Hydra/Helper/Nix.pm
src/lib/Hydra/Plugin/BitBucketPulls.pm
src/lib/Hydra/Plugin/DarcsInput.pm
src/lib/Hydra/Plugin/GithubPulls.pm
src/lib/Hydra/Plugin/GithubRefs.pm
src/lib/Hydra/Plugin/GitlabPulls.pm
src/lib/Hydra/Plugin/PathInput.pm
src/lib/Hydra/Plugin/S3Backup.pm
src/lib/Perl/Critic/Policy/Hydra/ProhibitShellInvokingSystemCalls.pm
src/script/hydra-send-stats
t/Hydra/Plugin/gitea.t
t/perlcritic.pl
t/s3-backup-test.pl

All use of backticks and system() in shell mode has been conveniences, but it's not really needed and can potentially lead to shell injection code. This pull request gets rid of this pattern in the codebase and sets up a linter to avoid future cases.

Stop shelling out

---

README.md

No description needed. `activate` -> `activated,`

docs: tiny typo fix in README.md
