hydra-module.nix

In the long run we should add retry logic to hydra-init...

hydra-module: Don't assume hydra is running on localhost.

---

tests/evaluation-tests.pl
tests/jobs/git-rev-input.nix
tests/jobs/git-rev-update.sh

Wasn't completely sure how to specify a git input pegged to a specific rev, so I added a test to make sure it was working.

Add eval test for specific git revision

---

hydra-module.nix

trivial bug that prevents enabling debugging

hydra-module: fix debug attribute

---

README.md
hydra-module.nix
release.nix

Just 3 one-line changes so I thought they can live in one PR.
Please let me know if you want seperate PRs (either for these commit or in the future)

Trivial fixes (readme, comment, missing dependency in release.nix)

---

src/lib/Hydra/Controller/API.pm

Fix api/push-github

---

src/root/product-list.tt
src/root/static/css/hydra.css

This is a slight UI change to improve readability of the product list table.
Fixes #288
cc @edolstra @rickynils

product list: convert to a proper table

---

src/root/common.tt

Without these title tags, there is no tool tip on hover.

Build status: copy the alt attribute to the title attribute for on-hover tool tips.

---

doc/manual/installation.xml

Setting up hydra was a frustrating experience of searching through perl packages documentation and sources.
Also closes #214, this setup does work and is tested with master.

Document how to serve hydra behind reverse proxy

---

src/root/edit-jobset.tt
src/root/jobset.tt

This reverts commit c103163825340e7e8af2ecbc50489384a2346a01.
Fixes #412 #445 
Ping @domenkozar

Revert "Sort inputs table" (fix #412 #445)

---

src/hydra-queue-runner/queue-monitor.cc

Send BuildFinished notifications on cached build results.

---

src/lib/Hydra/Helper/AddBuilds.pm
src/lib/Hydra/Helper/Nix.pm

declarative projects: Pull jobset spec build from the remote store

---

hydra-module.nix

hydra-module.nix: restart daemons on config change

---

src/lib/Hydra/Plugin/BitBucketStatus.pm

Use build id for bitbucket Key

---

src/hydra-queue-runner/hydra-queue-runner.cc

hydra-queue-runner: ensure roots directory exists

---

src/lib/Hydra/Plugin/BitBucketPulls.pm

Basically a copy of the Github plugin, adapted to the BitBucket API.

Add BitBucket pull request support

---

src/hydra-queue-runner/build-remote.cc

The hydra-queue-runner opens a connection to the builder. If the
builder is 'localhost' it starts `nix-store`, otherwise it starts
'ssh'.
Currently, if the hydra-queue-runner can not start `nix-store` (not in
the PATH for instance), the error message is:
cannot connect to ‘localhost’: error: cannot start ssh: No such file
or directory
This is not useful since ssh is actually not started:/
With this patch the error message is now:
cannot connect to ‘localhost’: error: cannot start nix-store: No such file
or directory

hydra-queue-runner: better error message if nix-store can not be started

---

src/lib/Hydra/Controller/Root.pm
tests/api-test.pl

I really don't know how to let Catalyst exports the result of a query as JSON. So, I've tried a way... but it could be completely wrong:/

Add JSON search API endpoint 

---

doc/manual/projects.xml

Corrected grammar typo

---

release.nix
src/lib/Hydra/Controller/Root.pm

Currently only shows per-machine build times

export a /prometheus endpoint

---

src/lib/Hydra/Helper/AddBuilds.pm

Fix declarative flake builds

---

src/lib/Hydra/Controller/Job.pm
src/lib/Hydra/Controller/Jobset.pm
src/lib/Hydra/Schema/Builds.pm
src/lib/Hydra/Schema/Jobs.pm
src/lib/Hydra/Schema/Jobsets.pm
src/script/hydra-eval-jobset
src/sql/hydra.sql
src/sql/upgrade-63.sql
src/sql/upgrade-64.sql
src/sql/upgrade-65.sql

Jobset id pgsql part 2

---

src/lib/Hydra/Plugin/SlackNotification.pm

Apart from documenting the plugin and its options, add some print debug statements, to track how well the plugin is doing.

Document SlackNotifications plugin

---

src/hydra-queue-runner/builder.cc
src/hydra-queue-runner/hydra-queue-runner.cc
src/hydra-queue-runner/queue-monitor.cc

Fix build against latest Nix

---

.github/workflows/test.yml

To avoid breakages as in: https://github.com/NixOS/hydra/pull/731

add github ci tests

---

src/lib/Hydra/Helper/Nix.pm

This method has been moved to hydra-eval-jobset a long time ago.

Remove dead method from Nix.pm

---

.github/dependabot.yml

Same as https://github.com/NixOS/nix/pull/3757

automatically update github actions

---

src/lib/Hydra/Plugin/HipChatNotification.pm
src/lib/Hydra/Plugin/SlackNotification.pm

Also standardize the slack image size on 256 pixels.
I have not tested the hipchat change, but am running something very similar on our slack setup.

Remove image dependency on hydra.nixos.org

---

src/lib/Hydra.pm

This is annoying and mostly redundant to nginx.

Disable access log

---

src/lib/Hydra/Helper/AddBuilds.pm

Fixes this error:
ERROR: failed to process declarative jobset test:inputs,
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st
execute failed: ERROR:  null value in column "emailoverride" violates
not-null constraint
cc @basvandijk

Stop violating not null constraint

---

src/hydra-queue-runner/nar-extractor.cc

nix change: https://github.com/NixOS/nix/commit/faa31f40

Update for receiveContents taking string_view

---

src/hydra-eval-jobs/hydra-eval-jobs.cc

This updates hydra to be compatible with Nix https://github.com/NixOS/nix/pull/4355.
Along with https://github.com/NixOS/hydra/pull/840 needed for https://github.com/NixOS/nixpkgs/pull/107909
/cc @edolstra

Update for Nix Value::type API changes

---

src/lib/Hydra/Controller/Root.pm
src/lib/Hydra/Controller/User.pm
src/root/topbar.tt
src/script/hydra-create-user
src/sql/hydra.sql

Requires the following configuration options
`github_client_id`
`github_client_secret` or `github_client_secret_file`

Implement GitHub logins

---

src/lib/Hydra/Controller/Root.pm

Even 20s is really long, but it cuts off queries which are today
running for 500+s.

search: limit queries to 20s

---

src/lib/Hydra/Plugin/GithubStatus.pm

Without this, only non-flake jobsets are sent GitHub status updates.
This is implemented by checking whether the flake is of the form `github:$owner/$repo/$rev`, and sending the status update to that repository. Note that the `$rev` is automatically determined, so jobsets with just the flake `github:$owner/$repo` work too.
The `githubstatus->inputs` configuration isn't used in that case.
I have tested this with both a flake jobset and a legacy jobset, both of which successfully update GitHub statuses now.

Fix Github status plugin for flakes

---

src/hydra-queue-runner/build-remote.cc

This would start happening if the network connection between the Hydra
server and the remote build server breaks after sucessfully importing
at least one output of a derivation, but before having finished
importing all outputs.
Fixes #816.

Fix persistent hash mismatch errors when importing

---

hydra-module.nix

This will make it easier to track specifically where queries are being
made from (assuming a `log_line_prefix` that includes `%a` in the
postgres configuration).
x-ref: https://github.com/NixOS/nixpkgs/pull/115024

module: append `application_name` to HYDRA_DBI

---

doc/manual/src/installation.md
src/lib/Hydra/Helper/Nix.pm
src/script/hydra-eval-jobset
src/script/hydra-send-stats
t/Config/statsd.t

Co-authored-by: Graham Christensen <graham@grahamc.com>
originally PR'd in #269 and updated, with tests and documentation. cc @matejc

statsd: add a chance to set hostname and port in hydra.conf

---

src/lib/Hydra/Plugin/RunCommand.pm
t/plugins/runcommand.t

DRAFT: I'd like to get some feedback from hydra users first. It feels a bit rude to break the compatibility of this field, but I'd quite like to clean up the campsite a bit.

RunCommand: emit the `finished` field as a boolean

---

src/script/hydra-send-stats
t/lib/Setup.pm
t/scripts/hydra-send-stats.t

fixes https://github.com/NixOS/hydra/issues/894

hydra-send-stats: fix imports

---

src/lib/Hydra/Controller/Root.pm
src/lib/Hydra/Helper/Nix.pm

The rows otherwise are often improperly zebra striped.

Projects, jobsets: order jobsets with disabled, hidden rows at the end

---

flake.lock
src/hydra-queue-runner/build-remote.cc

Fix the build failure introduced by NixOS/nix@9b9e703df41d75949272059f9b8bc8b763e91fce

Fix build with latest master

---

hydra-api.yaml
src/lib/Hydra/Controller/Project.pm
src/lib/Hydra/Helper/CatalystUtils.pm

Closes https://github.com/NixOS/hydra/issues/926.

Return HTTP 400 when creating Project with nonexistent user

---

src/lib/Hydra/Component/ToJSON.pm
src/lib/Hydra/Schema/Projects.pm
t/Controller/projects.t

Fixes https://github.com/NixOS/hydra/issues/929.

Serialize `enabled` and `hidden` columns as boolean

---

src/hydra-queue-runner/hydra-queue-runner.cc
t/Makefile.am
t/default-machine-file.t
t/jobs/default-machine-file.nix
t/lib/Setup.pm

Include localhost's features in the default machine file

---

src/lib/Hydra/Schema/JobsetInputs.pm
src/lib/Hydra/Schema/Jobsets.pm

Fixes a deploy issue, not sure why it wasn't caught in CI. I'll dig in to that shortly.

Jobsets,JobsetInputs: use JSON

---

hydra-api.yaml
src/lib/Hydra/Controller/Jobset.pm
t/Controller/Jobset/http.t

Fixes https://github.com/NixOS/hydra/issues/946.

Jobset: list known inputs in invalid input type response

---

src/lib/Hydra/Controller/Project.pm
t/api-test.t

Fixes https://github.com/NixOS/hydra/issues/949.

Fix deleting projects

---

hydra-module.nix

This is needed to evaluate the module on 21.05.
cc @grahamc

Set `isSystemUser = true;` for each statically declared user

---

doc/manual/src/SUMMARY.md
doc/manual/src/monitoring/README.md
flake.nix
src/lib/Hydra.pm
t/Controller/metrics.t

Metrics look like:
```console
$ curl http://localhost:63333/metrics
http_request_duration_seconds_bucket{action="queue_runner_status",code="200",controller="Hydra::Controller::Root",le="0.005",method="GET"} 0
http_request_duration_seconds_bucket{action="queue_runner_status",code="200",controller="Hydra::Controller::Root",le="0.01",method="GET"} 0
http_request_duration_seconds_bucket{action="queue_runner_status",code="200",controller="Hydra::Controller::Root",le="0.025",method="GET"} 0
http_request_duration_seconds_bucket{action="queue_runner_status",code="200",controller="Hydra::Controller::Root",le="0.05",method="GET"} 0
http_request_duration_seconds_bucket{action="queue_runner_status",code="200",controller="Hydra::Controller::Root",le="0.075",method="GET"} 0 …
```

Prometheus Metrics for the Webserver

---

doc/manual/src/SUMMARY.md
doc/manual/src/notifications.md

Notes from what I learned testing and working with notifications.

Notifications: write up some docs

---

.perlcriticrc
README.md
flake.nix
src/lib/Hydra/Controller/User.pm
src/lib/Hydra/Helper/Nix.pm
src/lib/Hydra/View/NixClosure.pm
src/lib/Hydra/View/NixLog.pm
src/lib/Hydra/View/NixNAR.pm
t/Makefile.am
t/perlcritic.pl

I'm expecting this PR to fail, then I'll push a fixup commit making it pass.

Check the perl with perlcritic

---

hydra-api.yaml
src/lib/Hydra/Controller/Build.pm
t/Controller/Build/constituents.t
t/jobs/aggregate.nix

Returns a list of constituent builds.

add api endpoint: /build/<id>/constituents

---

src/lib/Hydra/Schema/Result/JobsetEvals.pm

/eval: Return more columns

---

README.md
doc/manual/src/hacking.md
doc/manual/src/notifications.md

Fix various typos in Markdown documentation files.

docs: fix typos

---

flake.nix

add missing develop dependency

---

t/plugins/runcommand.t

Cleans up the integration tests of runcommand.t.

Runcommand.t: minor cleanup

---

src/lib/Hydra/View/TT.pm
src/root/all.tt
src/root/build.tt
src/root/edit-jobset.tt
src/root/evals.tt
src/root/job.tt
src/root/jobset-eval.tt
src/root/jobset.tt
src/root/layout.tt
src/root/log.tt
t/View/TT.t

project:jobset:job: make clickable links in titles

---

flake.nix
src/lib/Hydra.pm
src/lib/Hydra/Controller/Root.pm
src/lib/Hydra/Event.pm
src/lib/Hydra/Helper/CatalystUtils.pm
src/script/hydra-eval-jobset
t/Controller/Root/narinfo.t
t/Helper/CatalystUtils.t

It's always bothered me, seeing warnings pop up while running Hydra locally (while testing something or another). So, I fixed a lot of them here. Some fixes may need extra attention, though.
---
TODO:

Fix some warnings

---

src/root/build.tt
src/root/dashboard.tt
src/root/jobset-eval.tt
src/root/jobset.tt

builds page: capitalize tabs

---

foreman/start-hydra.sh

Debug enables info and debug log levels and provides quite a lot of useful dev-time information.
Restart automatically restarts the app when the .pm files change.

foreman: run the dev server with --restart and --debug

---

src/root/static/css/hydra.css

Somewhat inspired by the dark GitLab theme.
Screenshots (don't worry about the wideness, the screenshots also include #965):

Provide a dark theme when the user prefers it

---

src/lib/Hydra/Controller/Jobset.pm
t/api-test.t

Cleans up a few places which would emit warnings during tests.

Api test warnings: clean up

---

src/lib/Hydra/Controller/JobsetEval.pm
src/lib/Hydra/Helper/BuildDiff.pm
src/root/jobset-eval.tt
t/Controller/JobsetEval/fetch.t
t/Helper/BuildDiff.t

This is the smallest change that will make this work. All my other ideas would have resulted in a larger refactoring.
---
Closes https://github.com/NixOS/hydra/issues/1088.
---
TODO:

Allow restarting failed builds even with no eval to compare to

---

src/lib/Hydra/Plugin/RunCommand.pm

RunCommand: update the source of project and jobset names

---

src/lib/Hydra/Helper/CatalystUtils.pm
src/lib/Hydra/Helper/Nix.pm
src/lib/Hydra/Schema/Result/Builds.pm
src/lib/Hydra/Schema/Result/Projects.pm
src/root/common.tt
t/Hydra/Controller/Build/constituents.t
t/Hydra/Controller/Job/builds.t
t/Hydra/Controller/Jobset/builds.t
t/Hydra/Controller/Project/builds.t

The picked commit in this case was `Builds: LatestSucceeded*`.

Builds table: replace some project and jobset references in the Projects and Builds controllers

---

src/lib/Hydra/Controller/Root.pm
t/Hydra/Controller/Root/status.t

The picked commit in this case was `queue summary: fix refs` and `machines: fixup refs`.

Project jobset columns: fixup /queue-summary and /machines

---

src/root/common.tt
t/Hydra/Controller/Root/status.t

The picked commit in this case was `common.tt: fixup refs`.
Note this one includes #1112.

Project jobset: update /steps

---

src/hydra-queue-runner/build-remote.cc

When having a builder like this in `/etc/nix/machines`
ssh://mfbuild?remote-store=/home/bosch/store
Hydra cannot build there since it tries to pass the entire value to
`ssh(1)` which doesn't work. Also, an alternate store-location is e.g.
used if the user isn't a trusted user on the remote system and thus
cannot use `/nix/store`.
If such a URI is given, Hydra will now add a `--store /home/bosch/store`
to the `ssh`-command to select the appropriate location remotely.

hydra-queue-runner: support store URIs declaring an alternate store location

---

flake.nix
hydra-module.nix
src/lib/Hydra/Controller/Build.pm
src/lib/Hydra/Controller/Root.pm
src/lib/Hydra/Helper/Nix.pm
src/lib/Hydra/Plugin/RunCommand.pm
src/lib/Hydra/Schema/Result/RunCommandLogs.pm
src/root/build.tt
src/root/log.tt
src/root/runcommand-log.tt
src/sql/hydra.sql
src/sql/upgrade-81.sql
t/Hydra/Helper/Nix.t
t/Hydra/Plugin/RunCommand/basic.t
t/Hydra/Plugin/RunCommand/http.t
t/Hydra/Plugin/RunCommand/json.t
t/Hydra/Schema/Result/RunCommandLogs.t

Contains https://github.com/NixOS/hydra/pull/1106.
TODO:

Store and display the output of RunCommands

---

flake.nix

Add more development dependencies.

missing develop dependencies

---

flake.nix

I personally use nixpkgs-fmt and am a bit annoyed every time I edit this file and find myself explicitly having to _not_ format the file.

flake.nix: format with nixpkgs-fmt

---

flake.lock
flake.nix
t/jobs/empty-dir-builder.sh

Update Nix to 2.6

---

src/hydra-queue-runner/build-remote.cc

On `hydra.nixos.org` the queue runner had child processes that were stuck handling an exception:
```
Thread 1 (Thread 0x7f501f7fe640 (LWP 1413473) "bld~v54h5zkhmb3"):
#0  futex_wait (private=0, expected=2, futex_word=0x7f50c27969b0 <_rtld_local+2480>) at ../sysdeps/nptl/futex-internal.h:146
#1  __lll_lock_wait (futex=0x7f50c27969b0 <_rtld_local+2480>, private=0) at lowlevellock.c:52
#2  0x00007f50c21eaee4 in __GI___pthread_mutex_lock (mutex=0x7f50c27969b0 <_rtld_local+2480>) at ../nptl/pthread_mutex_lock.c:115
#3  0x00007f50c1854bef in __GI___dl_iterate_phdr (callback=0x7f50c190c020 <_Unwind_IteratePhdrCallback>, data=0x7f501f7fb040) at dl-iteratephdr.c:40
#4  0x00007f50c190d2d1 in _Unwind_Find_FDE () from /nix/store/65hafbsx91127farbmyyv4r5ifgjdg43-glibc-2.33-117/lib/libgcc_s.so.1
#5 …
```

openConnection(): Don't throw exceptions in forked child

---

doc/manual/src/configuration.md

doc/manual: fixup configuration option name

---

src/root/static/css/hydra.css

I'm not a web designer or frontend developer, but it felt like I spent more time scrolling after the recent library upgrade, so I modified the css a bit.
Not sure if this is of interest to other users, but here we go.

Fit more content on screen

---

src/hydra-queue-runner/state.hh

hydra: fix localhost detection when protocol prefix are used

---

src/root/layout.tt
src/root/static/css/hydra.css

The effect is the same as the one on links in mail bodys on
https://lists.apache.org/

Add a squiggly line to the Hydra link on hover

---

src/root/auth.tt
src/root/topbar.tt

Use new Google for Web signin, the old way will be deprecated Mar 31st 2023

Use new Google for Web signin

---

flake.lock
flake.nix
src/hydra-eval-jobs/hydra-eval-jobs.cc
src/hydra-queue-runner/hydra-queue-runner.cc

Closes #1265.
Basically includes #1265 + fixes for Nix 2.13. __Note:__ tracking `2.13-maintenance` here because we need https://github.com/NixOS/nix/pull/7746 which is not yet released.
cc @dasJ @ajs124 @grahamc @lheckemann

Nix 2.13 + nixpkgs input update

---

flake.lock
src/hydra-queue-runner/build-remote.cc

Companion to already-merged https://github.com/NixOS/nix/pull/9560

Use `ServeProto::Serialise<UnkeyedValidPathInfo>` for `QueryValidPaths`

---

doc/manual/src/configuration.md

It took me far too long to find out how to do this properly, so I'm writing it down for posterity. If you want to start a configuration reference page in the docs, I'm happy to do some of that in this PR.

Document the `store_uri` parameter by way of example

---

src/hydra-queue-runner/build-remote.cc

Nix defines basically an identical struct for the same purpose, so let's just use that.

Replace `Child` with `SSHMaster::Connection`

---

src/hydra-queue-runner/build-remote.cc

Not sure why this doesn't work yet.
~~Depends on https://github.com/NixOS/nix/pull/9833~~

Use Nix's `SSHMaster`

---

flake.nix

Those are already part of autoreconfHook

Remove automake, libtool

---

flake.lock
src/hydra-queue-runner/hydra-queue-runner.cc

Simplify `StoreConfig::getDefaultSystemFeatures` call

---

src/lib/Hydra/Controller/Build.pm
src/lib/Hydra/Controller/Root.pm

Otherwise names with special characters like + break things.

urlencode drv names when fetching logs

---

flake.lock
flake.nix
src/hydra-eval-jobs/hydra-eval-jobs.cc

Flake lock file updates:
• Updated input 'nix':
'github:NixOS/nix/60824fa97c588a0faf68ea61260a47e388b0a4e5' (2024-04-11)
→ 'github:NixOS/nix/1c8150ac312b5f9ba1b3f6768ff43b09867e5883' (2024-04-23)
• Added input 'nix/flake-parts':
'github:hercules-ci/flake-parts/9126214d0a59633752a136528f5f3b9aa8565b7d' (2024-04-01)
• Added input 'nix/flake-parts/nixpkgs-lib':
follows 'nix/nixpkgs'
• Added input 'nix/pre-commit-hooks':
'github:cachix/pre-commit-hooks.nix/40e6053ecb65fcbf12863338a6dcefb3f55f1bf8' (2024-04-12)
• Added input 'nix/pre-commit-hooks/flake-compat':
follows 'nix'
• Added input 'nix/pre-commit-hooks/flake-utils':
'github:numtide/flake-utils/5aed5285a952e0b949eb3ba02c12fa4fcfef535f' (2022-11-02)
• Added input 'nix/pre-commit-hooks/gitignore':
follows 'nix'
• Added input …

Update to Nix 2.22

---

src/hydra-queue-runner/build-remote.cc

Use https://github.com/NixOS/nix/pull/10749

Dedup more protocol code

---

src/hydra-queue-runner/hydra-queue-runner.cc

Companion to https://github.com/NixOS/nix/pull/10763

Dedup with nix: use `nix::Machine::parseConfig`

---

src/hydra-queue-runner/build-remote.cc

This is from `hydra.nixos.org` today, so I am confident enough that it is good.
(cherry picked from commit 18466e83261d39b997a73bbd9f0f249c3a91fbeb)

queue-runner: try larger pipe buffer sizes

---

t/Hydra/Controller/Job/builds.t
t/Hydra/Controller/Jobset/http.t
t/Hydra/Controller/User/dashboard.t
t/api-test.t

This gives us better diagnostics when the test fails.

tests: use `like` for testing regexes

---

nixos-modules/hydra.nix

follow up from 99ca560d583239b1bc34485f2f719989642fa697
Adapted from https://github.com/NixOS/hydra/pull/1408

set a default for hydra-compress-logs service

---

src/hydra-queue-runner/build-remote.cc

This avoids some duplicated code, leveraging the same `StoreReference` type that also undergirds the machine file dedup we just did prior.
By using `LegacySSHStoreConfig`, we're also taking a baby step towards using the store interface rather than messing around with the protocol internals.

Use new `CommonSSHStoreConfig::createSSHMaster`

---

src/script/hydra-eval-jobset

(backport to nix-2.25) hydra-eval-jobset: do not wait on n-e-j inside transaction

---

src/hydra-queue-runner/build-remote.cc
src/hydra-queue-runner/hydra-queue-runner.cc
src/hydra-queue-runner/state.hh

(cherry picked from commit f23ec71227911891807706b6b978836e4d80edde)

Add metric for builds waiting for download slot

---

src/root/machine-status.tt

web: increase colspan for machine row in machine status

---

flake.nix

error: access to absolute path '/nix/store/sai35xfsrba2a2vasmzxakmn54wdfa13-sourcepackaging' is forbidden in pure evaluation mode (use '--impure' to override)

Add missing slash

---

src/lib/Hydra/Controller/Root.pm
src/root/common.tt
src/root/machine-status.tt

- Fixes build graphs
- Fixes pagination
- Fixes pressure of new queue runner

Fix too much XSS protections
